### ISSUE TITLE
Cowboy 2.x requirement

### ISSUE THREAD

**Issue by fbjork** [newrelic/elixir_agent#10]
Any plans on supporting Cowboy 1.0? I think that would increase adoption of Phoenix based apps.

**Comment by binaryseed** [comment]
Hi, we leverage a feature in Cowboy 2.0 that ensures that each HTTP request is handled in it's own process.. w/o that, strange things happen when trying to track what transaction any given work was a part of...

I don't use Phoenix myself, but it looks like Phoenix `master` now has support for cowboy 2, so it's likely that support is right around the corner...

**Comment by fbjork** [comment]
@binaryseed Makes sense. Hopefully Phoenix 1.4 lands soon.

Are you planning on supporting Phoenix and Ecto in this library? If so will you accept PRs?

**Comment by binaryseed** [comment]
We're open to framework instrumentation beyond `Plug`, but we'd like to go the direction of making this project extensible so that there could be a package (something like `new_relic_phoenix` where that logic could live, and it could post data into this newrelic application. Mind opening an issue for those so we can track them as feature requests?

**Comment by fbjork** [comment]
@binaryseed sure thing, just created a separate issue for a Phoenix library.

**Comment by binaryseed** [comment]
I'll keep this open until Phoenix supports cowboy 2 out of the box..

**Comment by sb8244** [comment]
What would the error be like if overridden? Would it fail to report that transaction, or something worse?

**Comment by binaryseed** [comment]
Yes, it'd be a failure to report some data, it wouldn't impact the request at all. All reporting is done in a supervision tree separate from your running application.

**Comment by binaryseed** [comment]
That actually looks like the agent timed out trying to send data to New Relic, which I think would be unrelated to this issue.

**Comment by binaryseed** [comment]
FYI, Looks like a `rc` of 1.4 is out:

https://github.com/phoenixframework/phoenix/blob/master/CHANGELOG.md#140-rc0-2018-10-09

**Comment by fbjork** [comment]
Closing since Phoenix 1.4 is around the corner.
