### ISSUE TITLE
"no function clause matches" error in Transaction.Complete

### ISSUE THREAD

**Issue by axelson** [newrelic/elixir_agent#101]
**Describe the bug**
I am receiving a `no function clause matches` error on https://github.com/newrelic/elixir_agent/blob/v1.9.0/lib/new_relic/transaction/complete.ex#L27

I am not sure what `transform_name_attrs/1` is actually receiving

The stacktrace from honeybadger is just:
```
lib/new_relic/transaction/complete.ex:27:in `transform_name_attrs/1'
lib/new_relic/transaction/complete.ex:12:in `run/2'
lib/task/supervised.ex:89:in `do_apply/2'
proc_lib.erl:249:in `init_p_do_apply/3'
```

**Environment**
* Elixir & Erlang version (`elixir -v`): 1.7.4 Erlang/OTP 21 [erts-10.2.3]
* Agent version (`mix deps | grep new_relic_agent`): `* new_relic_agent (Hex package) (mix) locked at 1.9.0 (new_relic_agent) 6d8d4332`

**Comment by binaryseed** [comment]
thanks! this happens sometimes when the agent doesn't receive required attributes in a transaction (ex: `end_time`)

I'll try to find some time to update it to handle those cases directly

**Comment by axelson** [comment]
Thanks for the quick fix!

**Comment by romul** [comment]
@axelson This one is still active. I got:
```
lib/new_relic/transaction/complete.ex:43 in (new_relic_agent 1.27.6) NewRelic.Transaction.Complete.transform_time_attrs(%{end_time_mono: -576438431974033763, name: "Unknown/Unknown", process_spawns: []})
lib/new_relic/transaction/complete.ex:13 in (new_relic_agent 1.27.6) NewRelic.Transaction.Complete.run/2
lib/new_relic/transaction/sidecar.ex:224 in (new_relic_agent 1.27.6) NewRelic.Transaction.Sidecar.handle_continue/2
gen_server.erl:695 in (stdlib 3.17) :gen_server.try_dispatch/4
gen_server.erl:437 in (stdlib 3.17) :gen_server.loop/7
proc_lib.erl:226 in (stdlib 3.17) :proc_lib.init_p_do_apply/3
```

new_relic_agent 1.27.6
Elixir 1.12.3 (compiled with Erlang/OTP 24)
