### ISSUE TITLE
App Name is incorrect

### ISSUE THREAD

**Issue by axelson** [newrelic/elixir_agent#102]
**Describe the bug**
We are deployed on Heroku and a few days ago our app name started to be incorrect. We use the environment variables for configuration:

```
jason@Jasons-MacBook-Pro-2 ~/n/messages> heroku config|grep NEW_RELIC
 ›   Warning: heroku update available from 7.21.0 to 7.22.3
NEW_RELIC_APP_NAME:                                My App Production
NEW_RELIC_LICENSE_KEY:                             <key>
NEW_RELIC_LOG:                                     stdout
```

However, the app name in New Relic is `"My App Production (Elixir)"`, the old `"My App Production"` still exists but no data is being recorded to it. Do you have any idea what might be causing this?

**Environment**
* Elixir & Erlang version (`elixir -v`): 1.7.4 Erlang/OTP 21 [erts-10.2.3]
* Agent version (`mix deps | grep new_relic_agent`): `* new_relic_agent (Hex package) (mix) locked at 1.9.0 (new_relic_agent) 6d8d4332`

**Comment by binaryseed** [comment]
Hello, so if you have an app that was already reporting to New Relic, it can't start reporting with a new Agent language (thus the `Elixir` tacked onto the end). It was probably reporting previously as a different language (i'm guessing you used one of the open source elixir agents and it reported as `python`)

**Comment by axelson** [comment]
No we've been using only this library for this project. And a week ago when we did a upgrade to ecto 3 (and cowboy 2) the name changed. Not super important, but it's annoying since I have to update our monitoring dashboard to use the new app/name.

**Comment by binaryseed** [comment]
hmm, mind sending me an email vince@newrelic.com , I can look further into it

**Comment by axelson** [comment]
Sent! Thanks.
