### ISSUE TITLE
ability to configure log level

### ISSUE THREAD

**Issue by ananthakumaran** [newrelic/elixir_agent#104]
We currently use the `Logger` option for `new_relict_agent.logger`. We set the application log level to `:info`, but info level doesn't seem to be ideal level for new_relic_agent

```
new_relic_agent - Completed Error Event harvest - size: 0
new_relic_agent - Completed Span Event harvest - size: 86
new_relic_agent - Completed Metric harvest - size: 20
new_relic_agent - Completed Error Trace harvest - size: 0
new_relic_agent - Completed Custom Event harvest - size: 68
new_relic_agent - Completed Transaction Trace harvest - size: 0
new_relic_agent - Completed Transaction Event harvest - size: 12
new_relic_agent - Completed Metric harvest - size: 20
new_relic_agent - Completed Transaction Trace harvest - size: 0
```

We are not interested in the above information and would probably be only interested in warnings/errors. is there any way to control the log level of the agent? I initially thought I could use [compile time purging](https://hexdocs.pm/logger/Logger.html#module-application-configuration), but as new_relic_agent uses `Logger.log` directly, I am not sure whether anything could be done at compile time.

**Comment by binaryseed** [comment]
Hello! what version of the agent are you running?

**Comment by binaryseed** [comment]
Those messages are currently logged at `info`, so it makes sense that you are seeing them in your log.

**Comment by ananthakumaran** [comment]
we are using the latest version 1.9.2
