### ISSUE TITLE
Make `apdex_t` configurable

### ISSUE THREAD

**Issue by binaryseed** [newrelic/elixir_agent#106]

**Comment by emerleite** [comment]
This is related with this other issue? https://github.com/newrelic/elixir_agent/issues/86

**Comment by binaryseed** [comment]
I'm going to close this since Apdex threshold is configurable via:

```
config :new_relic_agent, apdex_t: 2.5 
```

The value is in seconds.

There's a separate issue regarding "Server Side Config"
