### ISSUE TITLE
Support scoped metrics

### ISSUE THREAD

**Issue by adityaU** [newrelic/elixir_agent#107]
is there a way to show traces in breakdown table and App server breakdown Graphs?

**Comment by binaryseed** [comment]
Hi, could you explain your question a little more please?

**Comment by adityaU** [comment]
Okay. When I add @trace with or without category external/datastore.  It shows up in individual transactions as spans. It also shows up in database / external services tabs, but it doesn't show up in breakdown table below throughput graphs on transaction details page. It also doesn't show up in graphs.

**Comment by binaryseed** [comment]
Ahh, I see now. Those breakdown tables are powered by "scoped metrics" which the agent doesn't currently support.

You might want to explore the Distributed Tracing feature however, because those traced functions show up as `Span` events in Insights which can be further queried...

**Comment by adityaU** [comment]
is there a plan to support "scoped Metrics" ?

**Comment by binaryseed** [comment]
I don't have a plan to support them.. I haven't had any requests aside from this question. I'll log this as a feature request
