### ISSUE TITLE
Seeing `Erlang error: {:key_exists, ...}` from the agent

### ISSUE THREAD

**Issue by jasondew** [newrelic/elixir_agent#108]
**Describe the bug**

We're seeing a few error reports daily with the following error message:

```
Erlang error: {:key_exists, {2688, 1554362690713334865}}
```

coming from `lib/new_relic/sampler/top_process.ex:51:in measure_and_insert/2`.

**Environment**
* Elixir & Erlang version (`elixir -v`): 1.8.1
* Agent version (`mix deps | grep new_relic_agent`): 1.8.0

**Comment by binaryseed** [comment]
Ahh interesting, there must be to processes sampled simultaneously that have the exact same memory size. Thanks! i'll review your PR

**Comment by jasondew** [comment]
@binaryseed I think so too, thanks!
