### ISSUE TITLE
Local development 500s lose their stacktraces?

### ISSUE THREAD

**Issue by coladarci** [newrelic/elixir_agent#111]
**Describe the bug**
The moment we include `new_relic_agent`, even if we don't configure it or reference it anywhere, local 500s lose their stack traces making it impossible to diagnose problems.

This is obviously frustrating as our ops team loves the integration in production but we are forced to remove it from our mix files (as well as comment out all the places that configure it) to get any work done.

Is it reasonable to expect the plugin to have no affect on our app if it's not configured? This is how Sentry and Appsignal work; behavior we've come to expect.

Example:
Simply by including `new_relic_agent` in our application, w/ no references to it anywhere:
```
14:38:52.634 request_id=956da5e18863478bf4cc6a0f20365dcc [info] GET /consumer/programs/8wWw
14:38:52.657 request_id=956da5e18863478bf4cc6a0f20365dcc [debug] Processing with ConsumerWeb.ProgramController.show/2
14:38:52.693 request_id=956da5e18863478bf4cc6a0f20365dcc [info] Sent 500 in 58ms
```
when we comment out that line from our deps, the same request:
```
14:41:31.063 request_id=2df4a040ffa54883af01c902ba5c7e62 [info] GET /consumer/programs/8wWw
14:41:31.114 request_id=2df4a040ffa54883af01c902ba5c7e62 [debug] Processing with ConsumerWeb.ProgramController.show/2
14:41:31.167 request_id=2df4a040ffa54883af01c902ba5c7e62 [info] Sent 500 in 103ms
14:41:31.179 [error] #PID<0.3230.0> running API.Endpoint (connection #PID<0.3229.0>, stream id 1) terminated
Server: noreaga:80 (http)
Request: GET /consumer/programs/8wWw
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in ConsumerWeb.ProgramResolverFixture.program_by_id/2
        stack trace continues...
```

Thanks for any guidance here!

**Environment**
* Elixir & Erlang version: `Elixir 1.8.1 (compiled with Erlang/OTP 21)`
* Agent version: `1.9.5`

**Comment by binaryseed** [comment]
You don't have `use NewRelic.Transaction` in your plug pipeline?

**Comment by coladarci** [comment]
I do for production, but locally, I've removed it all to isolate the issue; adding this one line to our mix file removes stack traces... Is this expected behavior?

**Comment by binaryseed** [comment]
I tried to reproduce this with a raw `plug` based app, but I didn't see the same behavior. Even when I turned the agent on, the stacktrace is still logged... 

There must be something else going on here, not quite sure what it could be...

**Comment by coladarci** [comment]
Thanks for taking the time - I've noticed that there are a handful of different things that happen:

1) ECTO errors are the ones who tend to be hidden
2) even when the logs omit the stack trace, they are still returned to the client, so if you know to inspect the client response you can typically get what you need
3) Absinthe presents a special set of issues, but I suspect those are specific to that extension.

**Comment by binaryseed** [comment]
Hmm, I don't see how the agent would even impact that, we just install a `:logger` handler, which can't impact any other logger handler..

would you mind sharing your dependency list?

**Comment by binaryseed** [comment]
Closing until further information is provided
