### ISSUE TITLE
Phoenix library

### ISSUE THREAD

**Issue by fbjork** [newrelic/elixir_agent#12]
I would really like to see a separate library (e.g new_relic_phoenix) with Phoenix instrumentation support. That library should probably come with Ecto support out of the box too.

**Comment by fbjork** [comment]
@binaryseed Mostly plug and play instrumentation for Phoenix apps. Getting controller/action names properly instrumented along with Ecto instrumentation support.

**Comment by axelson** [comment]
Without deeper Phoenix integration the transactions list is not as helpful as it could be. This is what mine looks like:
<img width="433" alt="screenshot 2018-09-20 10 13 35" src="https://user-images.githubusercontent.com/9973/45844381-ef093900-bcbd-11e8-8e1e-66616210fc78.png">

But it's still a lot better than nothing!

**Comment by chollier** [comment]
hey! excited to see that new relic now has an Elixir agent, thanks for doing that :) we would love to see some kind of out of the box instrumentation with Phoenix, a la RoR for instance: Ecto transactions, Endpoint / transaction names..

**Comment by GregMefford** [comment]
To potentially save you some research, there's probably not a whole lot of code required to get this kind of instrumentation integrated. Here's how we do it in Spandex: https://github.com/spandex-project/spandex_phoenix/blob/master/lib/spandex_phoenix/instrumenter.ex

**Comment by sb8244** [comment]
A co-worker started on this. I'll follow up with him to see if he wants to pr it. If not I'll take it on. Will follow up soon

**Comment by fbjork** [comment]
@binaryseed thoughts on creating a new repo called newrelic_phoenix where the community can contribute to?

**Comment by beardedeagle** [comment]
@fbjork have you looked at `telemetry`? This is what they are planning on integrating with phoenix sometime down the line for 1.4 and are adding to ecto 3.0.

https://github.com/elixir-telemetry/telemetry

**Comment by binaryseed** [comment]
I definitely want to align the New Relic agent with `telemetry` and phoenix `instrumenter` style instrumentation going forward. I imagine a package like `new_relic_phoenix` would be a very thin shim that plugged into the hooks and made simple calls to `new_relic_agent` API functions...

What I think we need before that happens is to assess what the various hooks in Phoenix and Ecto are, what data they provide, and then I can figure out if we have the sufficient API functions in the agent. Lots are there but we may need to add more to enable some of this.

**Comment by binaryseed** [comment]
I found some time this past weekend and put together a small Phoenix adapter for the agent. I published a `rc` for folks who want to give it a spin:

https://github.com/binaryseed/new_relic_phoenix
https://hex.pm/packages/new_relic_phoenix/0.1.0-rc.0

It does everything the `Plug` instrumentation does, as well as better Phoenix Transaction naming and some basic Phoenix attributes.

I'm very open to suggestions for naming conventions, I don't run any Phoenix apps myself...

I also started an Ecto adapter but haven't gotten to that yet..

https://github.com/binaryseed/new_relic_ecto

**Comment by binaryseed** [comment]
Closing this now that we have https://github.com/binaryseed/new_relic_phoenix
