### ISSUE TITLE
Traced functions reporting PIDs instead of `ModuleName.function_name`

### ISSUE THREAD

**Issue by mpiercy827** [newrelic/elixir_agent#121]
**Describe the bug**
I've installed the NewRelic agent and used the `NewRelic.Tracer` module to capture spans. However when I look at the trace details in the NewRelic dashboard, instead of `ModuleName.function_name` as described in the docs, I see PIDs:

![image](https://user-images.githubusercontent.com/10817843/60299612-f7903f00-98e1-11e9-9be3-56714f77d063.png)
 
Here is what our instrumentation looks like:
```elixir
# In our router
defmodule MyApp.Router do
  pipeline :pipeline do
    plug(NewRelic.Transaction)
    ...
  end

  ...
end
```

```elixir
# In the modules we are trying to instrument.
defmodule MyModule do
  ...
  use NewRelic.Tracer
  
  @trace :function
  def function(arg) do
    ...
  end

  @trace :other_function
  def other_function do
    ...
  end
end
```

Is this a bug with the agent or a configuration issue on our end?

**Environment**
* Elixir & Erlang version (`elixir -v`): Elixir 1.8.2 (compiled with Erlang/OTP 21)
* Agent version (`mix deps | grep new_relic_agent`): 1.9.11

**Comment by binaryseed** [comment]
Processes are traced in addition to the functions you manually trace. I'll look into this a little more though

**Comment by binaryseed** [comment]
I checked things out and there haven't been any bugs that I can find, are you sure those transactions are executing the functions you have traced?

**Comment by mpiercy827** [comment]
@binaryseed I've checked again, and the functions I've traced are being executed. The interesting thing is that I got these functions to be reported properly if I wrap them in an "Other" transaction, but not in a web transaction. Ideally, I would be able to have these wrapped in a web transaction using the NewRelic plug.

**Comment by binaryseed** [comment]
Interesting, I think I need more detail about the situation, want to email me? vince at newrelic dot com

**Comment by binaryseed** [comment]
Closing until further information is provided

**Comment by mpiercy827** [comment]
Sorry for not following up on this, but I started from scratch on my branch that included the NewRelic agent and everything started working as expected 👍sorry I don't have a more useful followup.

**Comment by binaryseed** [comment]
thanks!
