### ISSUE TITLE
dialyzer fails when using elixir_agent

### ISSUE THREAD

**Issue by acac99** [newrelic/elixir_agent#127]
**Describe the bug**
When using the elixir_agent we are having issue with making dialyzer happy. The code works fine (we can see the output in new relic website) but when we run dialyzer it comes up with an error. I believe it's caused by the elixir_agent because when we remove :new_relic_agent dependency and its setup code, dialyzer passes. 

Here is the dialyzer error:
```
[:asn1, :certifi, :compiler, :cowboy, :cowlib, :crypto, :elixir, :exsync, :hackney, :httpoison, :idna, :kernel, :logger, :metrics, :mime, :mimerl, :plug, :plug_cowboy, :plug_crypto, :public_key, :ranch, :reverse_proxy_plug, :ssl, :ssl_verify_fun, :stdlib]
Looking up modules in dialyxir_erlang-22.0.4_elixir-1.9.0_deps-dev.plt
Finding applications for dialyxir_erlang-22.0.4_elixir-1.9.0_deps-dev.plt
Finding modules for dialyxir_erlang-22.0.4_elixir-1.9.0_deps-dev.plt
Removing 10 modules from dialyxir_erlang-22.0.4_elixir-1.9.0_deps-dev.plt
:dialyzer.run error: Analysis failed with error:
Could not scan the following file(s):
  Could not get Core Erlang code for: anubis/_build/dev/lib/certifi/ebin/certifi.beam

Last messages in the log cache:
  Reading files and computing callgraph...
Checking 733 modules in dialyxir_erlang-22.0.4_elixir-1.9.0_deps-dev.plt
** (CaseClauseError) no case clause matching: {{:nocatch, {:dialyzer_error, [78, 111, 116, 32, 97, 32, 114, 101, 103, 117, 108, 97, 114, 32, 102, 105, 108, 101, 58, 32, 'hireup/anubis/_build/dev/lib/hackney/ebin/hackney_metrics.beam', 10]}}, [{:dialyzer_plt, :compute_md5_from_file, 1, [file: 'dialyzer_plt.erl', line: 543]}, {:dialyzer_plt, :compute_new_md5_1, 3, [file: 'dialyzer_plt.erl', line: 509]}, {:dialyzer_plt, :check_plt1, 3, [file: 'dialyzer_plt.erl', line: 479]}, {:dialyzer_plt, :"-subproc/1-fun-0-", 1, [file: 'dialyzer_plt.erl', line: 603]}]}
    dialyzer_cl.erl:250: :dialyzer_cl.check_plt/3
    dialyzer_cl.erl:183: :dialyzer_cl.plt_common/3
    dialyzer.erl:160: :dialyzer.run/1
    lib/dialyxir/plt.ex:209: Dialyxir.Plt.plt_run/1
    lib/dialyxir/plt.ex:202: Dialyxir.Plt.plt_check/2
    lib/dialyxir/plt.ex:146: Dialyxir.Plt.check_beams/3
    lib/dialyxir/plt.ex:43: Dialyxir.Plt.check_plt/4
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
```

Setup code:
in mix.exs
``` def application do
    [
      extra_applications: [:logger, :httpoison, :new_relic_agent],
      mod: {Interfaces.Application, []}
    ]
  end
```

in our entry point code 
```  
use Plug.Router
if Mix.env() == :prod, do: use(NewRelic.Transaction)
```

Would you guys know what the reason is?

**Environment**
* Elixir & Erlang version (`elixir -v`): elixir 1.9.0 and Erlang/OTP 22
* Agent version (`mix deps | grep new_relic_agent`): 1.9.12

**Comment by binaryseed** [comment]
Hi there, I'm not seeing anything in the output that would suggest that it's the agent that is causing the issue...

1) You don't need to put the agent in `extra_applications`, it's part of the list of started applications by default
2) Maybe dialyzer doesn't like that the code is only there in `:prod`? I'd suggest using configuration (or the lack thereof) to turn the agent off in various environments...

**Comment by acac99** [comment]
Have you managed to get it working with dialyzer? Would you be able to link me to a working demo so I can see where I went wrong?

**Comment by acac99** [comment]
Actually it works fine. It was because we had added it into the root mix file in the umbrella app. Once we moved it into each app, dialyzer stopped complaining
