### ISSUE TITLE
High CPU usage and stuck processes

### ISSUE THREAD

**Issue by chowda** [newrelic/elixir_agent#128]
**Describe the bug**
We're seeing new relic elixir processes getting stuck and chewing up our available CPU. After enough traffic these processes never die and continue to process while memory slowly grows and eventually our pods are killed and restarted.

Using the observer_cli (https://github.com/zhongwencool/observer_cli) to monitor what is using the most memory and allocated the most CPU work (reductions) we have seen that consistently `Elixir.Newrelic.Harvest.Collector.Tran`, `Elixir.NewRelic.Transaction.Monitor`, and especially `Elixir.NewRelic.Transaction.Reporter` topping our lists. After digging around this is our best guess:

`Elixir.NewRelic.Transaction.Reporter` seems to be the most harmful stuck process. The "Current Function" section always reports it is in `Elixir.Enum:-reduce/3-lists^foldl` and these are the processes reporting the largest reductions. 

Looking through the elixir docs and this code base our best guess is that it is stuck in `NewRelic.Sampler.Process.record_samples` https://github.com/newrelic/elixir_agent/blob/c3e20f8a7dbdbffbb9a29c1a0e1ae8209a5ac91e/lib/new_relic/sampler/process.ex#L50-L51

None of us here are well versed in Elixir and are trying our best to explain this. If I can provide any additional information please let me know what would be useful. I'll include a few screenshots as well. Most likely we will be removing new relic until we can get this issue resolved.

**Environment**
```
Erlang/OTP 21 [erts-10.3.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.8.1 (compiled with Erlang/OTP 21)
```
New Relic agents: 
1.9.4 (https://github.com/newrelic/elixir_agent/releases/tag/v1.9.4)
1.10.0 (https://github.com/newrelic/elixir_agent/releases/tag/v1.10.0)

![image](https://user-images.githubusercontent.com/933209/62974299-bfc75300-bdcc-11e9-9c48-d086f02f566e.png)
![Screen Shot 2019-08-13 at 1 19 47 PM](https://user-images.githubusercontent.com/933209/62974752-c0acb480-bdcd-11e9-8644-40ca84881cc8.png)

**Comment by binaryseed** [comment]
Those processes are responsible for gathering and reporting all the data.. Is bed to know more about what's happening to help...

What kind of traffic pattern does your app have? What's the throughput?

**Comment by chowda** [comment]
Hey sorry for the late response, I was out of office the beginning of this week.

Our app is set up as an umbrella app currently. There is a shared dependency on the DB app between the other two apps: `Kafka -> DB <- Web`

We ingest kafka topics and provide an internal graphql API endpoint to expose the data to consuming services. We have the new relic agent in the web app.

I'll post some screenshots of our traffic for the last 24 hours. I brought it down to 1 minute intervals so the data is easier to reason about.

Web API throughput:
![Screen Shot 2019-08-21 at 9 38 19 AM](https://user-images.githubusercontent.com/933209/63451296-beafaa80-c3f8-11e9-9f76-40339d2cdaa5.png)

Kafka throughput:
![Screen Shot 2019-08-21 at 9 42 57 AM](https://user-images.githubusercontent.com/933209/63451331-cff8b700-c3f8-11e9-9431-e653f38140b4.png)

**Comment by christianjgreen** [comment]
Hey guys sorry to necro post. I hit the sam exact issue last night and wanted to see if you had any insight on the problem.

**Comment by chowda** [comment]
Unfortunately we never found the root issue. The last thought was that it may have something to do with our graphql resolvers. I had to remove it from our app and wasn't able to provide enough context for @binaryseed to diagnose. It was consuming all of our CPU and I was barred from running it on our systems further.

@binaryseed was very responsive via email and was trying to help. Perhaps if you can provide more information he might re-open the issue. If you do find the issue, please let us know!

**Comment by binaryseed** [comment]
From what I could tell for @chowda it boiled down to a huge number of processes being spawned during a single HTTP request, there were upwards of 5000.. The agent tries to track the connection between processes to report that data on the Transaction, and it's just too much

@christianjgreen If you want to email me, I can take a closer look and see if we can get anywhere...

**Comment by christianjgreen** [comment]
@chowda thanks for the info!

@binaryseed Appreciate the feedback :) What is the best email to reach you at?

**Comment by binaryseed** [comment]
it's a few comments up in the thread...

**Comment by devonestes** [comment]
We hit this bug yesterday as well - here's some more information:

Our top 5 processes by reduction count:
```
[
  %{
    current_function: {Enum, :"-reduce/3-lists^foldl/2-0-", 3},
    name: nil,
    reductions: 302_541_183_867
  },
  %{
    current_function: {:gen_statem, :loop_receive, 3},
    name: nil,
    reductions: 2_425_914_641
  },
  %{
    current_function: {:gen_server, :loop, 7},
    name: ...,
    reductions: 2_116_742_382
  },
unai:slack_call:  20:32
these are the top 5 processes with most reductions
  %{
    current_function: {:gen_server, :loop, 7},
    name: ...,
    reductions: 2_045_292_061
  },
  %{
    current_function: {:gen_server, :loop, 7},
    name: ...,
    reductions: 1_718_894_420
  }
]
```

And the process info for the one with the huge outliers in reductions:
```
[
    current_function: {Enum, :"-reduce/3-lists^foldl/2-0-", 3},
    initial_call: {:proc_lib, :init_p, 5},
    status: :running,
    message_queue_len: 0,
    links: [#PID<0.3265.0>],
    dictionary: [
      "$callers": [#PID<0.32152.54>],
      "$initial_call": {NewRelic.Transaction.Reporter, :"-complete/2-fun-0-", 0},
      "$ancestors": [NewRelic.Transaction.TaskSupervisor, #PID<0.3264.0>,
       #PID<0.3258.0>, NewRelic.Supervisor, #PID<0.3254.0>]
    ],
    trap_exit: false,
    error_handler: :error_handler,
    priority: :normal,
    group_leader: #PID<0.3253.0>,
    total_heap_size: 2805586,
    heap_size: 318187,
    stack_size: 37,
    reductions: 336955596238,
    garbage_collection: [
      max_heap_size: %{error_logger: true, kill: true, size: 0},
      min_bin_vheap_size: 46422,
      min_heap_size: 233,
      fullsweep_after: 65535,
      minor_gcs: 40281
    ],
    suspending: []
  ]
```

**Comment by binaryseed** [comment]
@devonestes  Can you describe the kind of work the app is doing? If you want to dive into details with me, you can also send me an email at vince at ...

**Comment by binaryseed** [comment]
I'm going to close this particular Issue, but if folks find specific instances of high resource consumption, please open another Issue with details!

1.18 includes a refactor of some of the underlying trace storage to reduce contention, 1.19 has an optimization for metric memory usage, and I have more ideas in the works

**Comment by thbar** [comment]
@devonestes did the latest versions solve this for you? I'm about to try out NewRelic for an Elixir app, and would love your feedback. Thanks!

**Comment by devonestes** [comment]
Im no longer with that company (and they moved off NewRelic after the trial), so I have no idea how these might help with those problems.
