### ISSUE TITLE
Response time vs Elixir process time

### ISSUE THREAD

**Issue by garno** [newrelic/elixir_agent#134]
Hi,

I’ve deployed an Elixir application (based on Phoenix) recently and the NewRelic reporting doesn’t seem to make sense to me. Maybe I’m missing something but the Elixir metric is always twice as high as the _Response time_.

<img width="981" alt="Capture d’écran, le 2019-09-03 à 21 39 58" src="https://user-images.githubusercontent.com/27001/64219432-7b8f1600-ce93-11e9-8826-5f89a1421efb.png">

Am I missing something? Thanks for your help, the agent is working pretty well otherwise 😄 

**Environment**
* Elixir & Erlang version: 1.8.1
* Agent version: new_relic_agent 1.10.0

**Comment by binaryseed** [comment]
The `Elixir` line is the total time spent in the Transaction, which includes concurrent time spent in other processes, so I suspect there might be some extra processes involved here?

**Comment by garno** [comment]
That’s it! Thanks for the explanation.
