### ISSUE TITLE
Not able to use recon_trace

### ISSUE THREAD

**Issue by ananthakumaran** [newrelic/elixir_agent#137]
**Describe the bug**
We occasionally use `:recon_trace.calls({Module, function, :return_trace}, n)` in production to debug issue (if the logs are not sufficient to track down the issue). With new_relic_agent enabled, this leads to following error, although the trace appears to work

> ** can only have one tracer per process

1) is there any way to fix this?
2) if not possible, is it possible to disable/enable new_relic for the duration via remote_console? I tried to stop new_relic via Application.stop(x), but it didn't go well, as all the calls to newrelic modules were failing.

**Environment**
* Elixir & Erlang version (`elixir -v`):
```
Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.7.4 (compiled with Erlang/OTP 21)
```
* Agent version (`mix deps | grep new_relic_agent`):

new_relic_agent 1.9.3

**Comment by binaryseed** [comment]
Yes, we leverage the built in Erlang tracer, of which there can only be one at a time.

You might be able to turn it off with a call to `erlang.trace` http://erlang.org/doc/man/erlang.html#trace-3

```
:erlang.trace(:all, false, [])
```

Another approach would be to get the data you need via the agent (ie: you could put a function tracer on that function)

Is there something about the `recon_trace` you need in particular?

**Comment by ananthakumaran** [comment]
> iex(xxxx@127.0.0.1)5> :erlang.trace(:all, false, [])
> 0

I tried it, the error still happens

> Another approach would be to get the data you need via the agent (ie: you could put a function tracer on that function)
> Is there something about the recon_trace you need in particular?

There are two kinds of instrumentation. One is proactive, we make a guess on what would be useful and add logs/metrics/traces earlier. We could definitely use new_relic trace for these cases.

The second kind is reactive, where we try to figure out what's going on and most of the time, we won't have enough time to add logs/traces and re-deploy the code. We use recon extensively in these cases. So far we have solved memory leaks, tcp connection leaks, ets table growth and been able to find the root cause of message queue overload etc. To give a specific example, we enabled newrelic transaction on a long-running worker process which might make 1000s of http requests. This caused high memory usage. We tracked it back by looking at the size of ets tables controlled by newrelic.

we use recon_trace as an on the fly logger, so we can quickly see what's passed between functions. It also has a rate limiter which prevents from capturing too much data and crashing the node.

Given that we can have only one tracer, Ideal solution for us would be the ability to disable features that depends on tracer before starting the debugging session and reenable it back when we finish the debugging session.

**Comment by realcorvus** [comment]
If anyone is finding this issue by googling "can only have one tracer per process" while using the New Relic agent, updating my config to:

```
config :new_relic_agent,
  ...
   disable_erlang_trace: true
   
```

is how I was able to disable Erlang tracing.
