### ISSUE TITLE
Track request queueing

### ISSUE THREAD

**Issue by sb8244** [newrelic/elixir_agent#141]
**Is your feature request related to a problem? Please describe.**

Our app uses proxies to get through to the Phoenix server. We want to track time spent in proxy as request queueing.

**Describe the solution you'd like**

The same request queueing feature that Ruby has, based on `X-Request-Start` header

**Describe alternatives you've considered**

I have not

**Comment by sb8244** [comment]
Happy to spike on this a bit, per our convo on Slack.

**Comment by binaryseed** [comment]
Here's a start...

To support this, we need to report:
* A `WebFrontend/QueueTime` metric. Unit: Seconds
* A `queueDuration` attribute on the Transaction. Unit: Seconds

Inside `NewRelic.Transaction.Plug` we'd add a new `maybe_report_queuing` function which we'd call from `on_call`

We need to read the `x-request-start` header, and handle potential clock skew (ie: don't log a negative queue time)

**Comment by sb8244** [comment]
Do you handle clock skew by just having a `max(timing, 0)` check? So if it did skew, it would just come across as 0?

**Comment by binaryseed** [comment]
I think that makes sense, in the case of a negative queue_time, it looks like Ruby treats that as `0`.. 

* https://github.com/newrelic/rpm/blob/17734c85a9251ede14fbee517f0d264d99116c7e/lib/new_relic/agent/instrumentation/queue_time.rb#L43

Also, we need to handle `x-request-start` as either Int or Float, and Seconds / Milliseconds / Microseconds
