### ISSUE TITLE
Prevent logging of @trace args

### ISSUE THREAD

**Issue by sb8244** [newrelic/elixir_agent#157]
**Is your feature request related to a problem? Please describe.**
Traced functions are so fast to use and work great, but they include the `args` of the function, and that contains a private API key in my case.

**Describe the solution you'd like**
I'd like all of the same tracing, but the args marked as `[]` or `[:redacted]`

**Describe alternatives you've considered**
I am thinking about finding a way to structure the function without accepting the input. Unfortunately I don't see a way yet. I am also considering replicating what `@trace` does, but that ends up being fairly complex.

**Comment by sb8244** [comment]
Oh this might work: 

```elixir
  @trace {:fetch_resources, category: :external}
  def fetch_resource_wrap(base, func) do
    NewRelic.set_span(:http, url: base, method: "GET", component: "MyApi")
    func.()
  end
```

**Comment by binaryseed** [comment]
We've thought about this before as well, probably an addition to the `@trace` is what we should do

**Comment by sb8244** [comment]
That would make sense.

Are you open to a PR or would you like to tackle this?
