### ISSUE TITLE
edeliver hot upgrades disconnect agent

### ISSUE THREAD

**Issue by silva96** [newrelic/elixir_agent#158]
**Describe the bug**
Every time we do hot upgrades (`mix edeliver deploy upgrade to production`) the app stops reporting data to newrelic. It is solved by doing `mix edeliver restart production` but obviusly that breaks the purpose of doing hot upgrades.

**Environment**
* Elixir & Erlang version: Elixir 1.9.1, Erlang/OTP 22
* Agent version : 1.8.0

**Comment by rwke89** [comment]
it also happens to me

**Comment by npinilla** [comment]
me too

**Comment by baliagaleri** [comment]
👍 i’ve experiencied the same problem.

**Comment by LestatAlmasy** [comment]
happens in my production server too, ubuntu 16 :(

**Comment by binaryseed** [comment]
Ok, hello there folks - I'm guessing ya'll work at the same place? :)

Can someone provide more details about how your deploy process is configured? Is there a small reproduction case that would help me observe the behavior?

**Comment by silva96** [comment]
Hi Vince, you got us haha, yes we work at the same place.

Look, we have a simple Phoenix app with the following deps:

```
defp deps do
    [
      {:phoenix, "~> 1.4"},
      {:phoenix_pubsub, "~> 1.1"},
      {:httpoison, "~> 1.5"},
      {:gettext, "~> 0.16"},
      {:plug_cowboy, "~> 2.0"},
      {:jason, "~> 1.1"},
      {:redix, "~> 0.9"},
      {:timex, "~> 3.4"},
      {:elixir_xml_to_map, "~> 0.1"},
      {:xml_builder, "~> 2.1"},
      {:credo, "~> 1.0", only: [:dev, :test], runtime: false},
      {:amqp, "~> 1.0"},
      {:apex, "~>1.2.1"},
      {:cors_plug, "~> 1.5"},
      {:guardian, "~> 1.1"},
      {:edeliver, ">= 1.6.0"},
      {:distillery, "~> 2.0", warn_missing: false},
      {:airbrakex, "~> 0.1.8"},
      {:new_relic_phoenix, "~> 0.1"}
    ]
  end
```

we have an ubuntu 16 build server where we do our builds using `edeliver`

edeliver provides the ability to do hot upgrades, but for some reason, after a hot upgrade the newrelic agent stops sending data. How can I help you debugging this? I see there is Supervisors for the agent but somehow it stops reporting.

**Comment by binaryseed** [comment]
I'd want to know more about how your release is configured, we can email to take this further... `vince@`

**Comment by silva96** [comment]
Here is a hot upgrade followed by a needed restart.

![image](https://user-images.githubusercontent.com/4019924/69658081-47725e00-105a-11ea-8676-76c9ffec67c8.png)

**Comment by binaryseed** [comment]
As this has gone a year now, I'm closing this. I haven't found time to investigate, and hot code reloads aren't a priority for me to support. Thanks folks!
