### ISSUE TITLE
Ecto telemetry fails

### ISSUE THREAD

**Issue by tmaszk** [newrelic/elixir_agent#171]
Since upgrading to new_relic_agent 1.15.0, database transactions are not uploaded to New Relic.

The issue seems to be that [Telemetry.Ecto.Handler](https://github.com/newrelic/elixir_agent/blob/4296c236e232d851783cef40c3706552e2f76ddd/lib/new_relic/telemetry/ecto/handler.ex#L18) expects config for `hostname:`, `port:` and `database:`, which are optional Ecto configuration fields.

Here's the top of the error log.
```
[error] Handler {:new_relic_ecto, :axdb} has failed and has been detached. Class=:error
Reason={:badmatch, %{database: "development", pool_size: 10}}
Stacktrace=[{NewRelic.Telemetry.Ecto.Handler, :handle_event, 4, [file: 'lib/new_relic/telemetry/ecto/handler.ex', line: 18]},
```

**Comment by binaryseed** [comment]
Thanks! fixed & about to release a patch version via #172
