### ISSUE TITLE
Browser Distributed Tracing breaks W3CTraceContext.TraceState

### ISSUE THREAD

**Issue by Dermah** [newrelic/elixir_agent#176]
**Describe the bug**
**Summary**: New Relic Browser Distributed Tracing doesn't seem to play nice with the new W3C Trace Context support.

----

I've just enabled [New Relic Browser Distributed Tracing](https://docs.newrelic.com/docs/browser/new-relic-browser/browser-pro-features/browser-data-distributed-tracing). The New Relic Browser agent adds a `newrelic` header to all front-end requests that go to our elixir back-end. At the moment it doesn't add the [newly announced W3C Trace Context headers](https://blog.newrelic.com/product-news/w3c-trace-context-distributed-tracing-standard/), apparently they'll be added at some point in the future.

During a transaction where the trace root is from the Browser agent, I'm trying to instrument an external call from the elixir back-end. [As described in the README](https://github.com/newrelic/elixir_agent#tracing), I set a span with `set_span/4` and then try to get the distributed trace headers with `distributed_trace_headers/1`, but I get this error:

```
12:27:48.209 [error] #PID<0.1164.0> running <redacted> (connection #PID<0.1163.0>, stream id 1) terminated
Server: localhost:8080 (http)
Request: GET /<redacted>
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.float_to_binary(nil, [:compact, {:decimals, 6}])
        (new_relic_agent) lib/new_relic/distributed_trace/w3c_trace_context/trace_state.ex:174: NewRelic.DistributedTrace.W3CTraceContext.TraceState.encode_priority/1
        (new_relic_agent) lib/new_relic/distributed_trace/w3c_trace_context/trace_state.ex:41: NewRelic.DistributedTrace.W3CTraceContext.TraceState.encode/1
        (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
        (new_relic_agent) lib/new_relic/distributed_trace/w3c_trace_context/trace_state.ex:26: NewRelic.DistributedTrace.W3CTraceContext.TraceState.encode/1
        (new_relic_agent) lib/new_relic/distributed_trace/w3c_trace_context.ex:83: NewRelic.DistributedTrace.W3CTraceContext.generate/1
        (new_relic_agent) lib/new_relic/distributed_trace.ex:43: NewRelic.DistributedTrace.distributed_trace_headers/1
        ...
```

Looks like something is going wrong while trying to generate the W3C Trace Context headers. 

The base 64 decoded `newrelic` header that Browser sent to the elixir back-end has the form (actual values replaced, but types are the same):

```json
{"v":[0,1],"d":{"ty":"Browser","ac":"1234567","ap":"234567890","id":"123ab456cd78e9f0","tr":"234b56cd789e0fa1","ti":1581385629189}}
```

The [`value` argument](https://github.com/newrelic/elixir_agent/blob/7d90c6ca02220bbbac4f9434f3406a73deeab5c2/lib/new_relic/distributed_trace/w3c_trace_context/trace_state.ex#L30) to `NewRelic.DistributedTrace.W3CTraceContext.TraceState.encode/1` when it errors has the form:

```elixir
%NewRelic.DistributedTrace.W3CTraceContext.TraceState.NewRelicState{
  account_id: "1234567",
  app_id: "987654321",
  parent_type: "App",
  priority: nil,
  sampled: false,
  span_id: "98765f4e3210987d",
  timestamp: 1581384478274,
  transaction_id: nil,
  trusted_account_key: nil,
  version: "0"
}
```

Sorry, I don't have a whole lot of elixir experience so please let me know if some other info would help.

**Environment**
* Elixir & Erlang version (`elixir -v`):
```
Erlang/OTP 22 [erts-10.5.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.9.1 (compiled with Erlang/OTP 22)
```
* Agent version (`mix deps | grep new_relic_agent`):
```
* new_relic_agent 1.16.2 (Hex package) (mix)
  locked at 1.16.2 (new_relic_agent) 9257dcbd
```

**Comment by binaryseed** [comment]
Thanks that was very helpful, I released a patch version `1.16.3`
