### ISSUE TITLE
Harvest debug calls being logged even with log level :warn?

### ISSUE THREAD

**Issue by buob** [newrelic/elixir_agent#178]
**Describe the bug**
`Logger.level()` yields `:warn`, yet I'm still seeing the following in our logs:

```
[DEBUG] - 2020-02-11 21:14:46 - Completed Transaction Event harvest - size: 0
[DEBUG] - 2020-02-11 21:14:51 - Completed Error Event harvest - size: 0
[DEBUG] - 2020-02-11 21:14:51 - Completed Custom Event harvest - size: 0
[DEBUG] - 2020-02-11 21:14:51 - Completed Transaction Event harvest - size: 0
[DEBUG] - 2020-02-11 21:14:56 - Completed Error Event harvest - size: 0
```

This might be a PEBKAC but it seems like the log level is being ignored somewhere in the pipeline.

**Environment**
* Elixir & Erlang version (`elixir -v`):
```
Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.9.1 (compiled with Erlang/OTP 22)
```

* Agent version (`mix deps | grep new_relic_agent`):
```
* new_relic_agent 1.16.2 (Hex package) (mix)
  locked at 1.16.2 (new_relic_agent) f8bf8594
```

Thanks!

**Comment by binaryseed** [comment]
New Relic agents default to writing log entries to a file, and don't use the default logger.

You can have NR logs sent to the elixir logger via `config :new_relic_agent, log: "Logger"`

In a hypothetical version 2 of the agent, I'd probably adopt the elixir logger exclusively, but for now we can't.

**Comment by buob** [comment]
I'm not sure I entirely understand @binaryseed, I'm sorry for being obtuse.

If that was the problem, wouldn't I be seeing to _few_ items logged, instead of too _many_?  I'm seeing the debug line items but I would expect to not see them at all.

**Comment by binaryseed** [comment]
How have you configured `new_relic_agent`?

**Comment by buob** [comment]
Just with `app_name` and `license_key`.  We're getting data into our new relic app, but when I run the `heroku log` command or run `iex` through heroku, that's where I'm getting the noise.

**Comment by buob** [comment]
Probably pertinent, I have both `new_relic_agent` and `new_relic_phoenix` in my dependencies, mostly because a good chunk of the reporting we need is in a worker and not in phoenix, but not sure if that was the right move.

**Comment by binaryseed** [comment]
hmm, logs should go to a file by default, I wonder if heroku sets some ENV variable to send it to stdout or something... can you tell what is in `NEW_RELIC_LOG` env var?

**Comment by buob** [comment]
🤦‍♂ 

Yup.

Is there anything valuable in new relic logs that I'd want sent to our logger? i.e. to Timber?  I guess my expectation would be that `stdout` would be fine and would respect my log level, but it's showing debug items.

**Comment by binaryseed** [comment]
if you configure `NEW_RELIC_LOG=Logger` it will use & respect the Logger level

**Comment by buob** [comment]
Ah, dots connected.

Thank you very much!
