### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by tvranicar** [newrelic/elixir_agent#179]
We are seeing two separate issues with the  agent for elixir:

1. When attempting to monitor functions in our jobs, we begin to see the NewRelic agent fail to complete all traces. Many traces do complete, but others are left open. With the rate of throughput, this quickly balloons memory to ~13GB, making the BEAM unresponsive.

2. Ecto Telemetry raises UnsupportedEctoAdapter, even though we're using Postgrex. Oddly, we get reporting for a short time before this occurs.

**Comment by tommytang21** [comment]
Egunderson
Feb 20, 07:52 PST

Stacktrace for the ecto telemetry issue:

Handler {:new_relic_ecto, :engine} has failed and has been detached. Class=:error
Reason=%RuntimeError{message: "Unsupported ecto adapter"}
Stacktrace=[{NewRelic.Telemetry.Ecto.Metadata, :parse, 1, [file: 'lib/new_relic/telemetry/ecto/metadata.ex', line: 54]}, {NewRelic.Telemetry.Ecto.Handler, :handle_event, 4, [file: 'lib/new_relic/telemetry/ecto/handler.ex', line: 28]}, {:telemetry, :"-execute/3-fun-0-", 4, [file: '/home/ec2-user/builds/master/b5e4e0b99f975672f1254cb0258f50af89ad3811/cars_platform/deps/telemetry/src/telemetry.erl', line: 123]}, {:lists, :foreach, 2, [file: 'lists.erl', line: 1338]}, {Ecto.Adapters.SQL, :log, 4, [file: 'lib/ecto/adapters/sql.ex', line: 792]}, {DBConnection, :log, 5, [file: 'lib/db_connection.ex', line: 1384]}, {DBConnection, :prepare_declare!, 4, [file: 'lib/db_connection.ex', line: 1202]}, {DBConnection, :"-reduce/3-fun-0-", 4, [file: 'lib/db_connection.ex', line: 996]}]

**Comment by binaryseed** [comment]
1) performance - we need to know more about what's happening here before we can try to help. what is the app doing?
2) ecto - we need to know the agent version (there's been a recent fix around this)

**Comment by tommytang21** [comment]
We’re on the latest release, 1.16.2, which has the last round of Ecto telemetry fixes. There is an RC out for 1.17.0 though. It looks primarily related to changes in the way external metrics are collected, but I’ll upgrade us and see if it resolves anything on our end.
-Ethan

**Comment by binaryseed** [comment]
Moving to the `rc` release is not necessary - the handler errored because it's seen a result that it doesn't know how to parse...

What ecto adapter are you using?

**Comment by ethangunderson** [comment]
Describe the bug
We're attempting to instrument a Broadway consumer and experiencing issues with memory usage. The code under instrumentation is part of an etl pipeline. It gets a message containing a reference  to an s3 file, fetches, processes, and then stores the results in a database. It is currently running as a Broadway consumer. This code was under instrumentation external to Broadway without issue.

The code looks something like this:

try do
  NewRelic.Transaction.Reporter.start_other_transaction(
    "Task",
    "#{unquote(inspect(module))}/perform"
  )
  do_the_work(args, job)
after
  info = Process.info(self(), [:memory, :reductions])
  NewRelic.add_attributes(
    memory_kb: info[:memory] / @kb,
    reductions: info[:reductions]
  )
  NewRelic.Transaction.Reporter.complete()
end

The Broadway process executes ~2-5 messages per second, so nothing too crazy. However, with this transaction in place memory usage spikes until it's fully consumed and the beam process crashes.

We've inspected the response the agent's harvester gets from sending the trace data, which I believe was {:ok, :accepted}, and we can see the transactions in Insights, but they do not appear in APM.

We've instrumented this code in other parts of the system without issue, so it definitely feels like it's related to Broadway. Any help here would be appreciated.

Environment

    Elixir & Erlang version (elixir -v): 1.9.0-otp-22
    Agent version (mix deps | grep new_relic_agent): 1.16.3

**Comment by ethangunderson** [comment]
> What ecto adapter are you using?
Postgrex

**Comment by binaryseed** [comment]
Ecto:

I'm published up a revision of the agent (`1.16.4`) that will better log the result that we aren't handling. There must be some edge case that causes the result to have a shape we've never seen before.

**Comment by binaryseed** [comment]
Let's talk about broadway in the issue you opened :)
