### ISSUE TITLE
Nested segments

### ISSUE THREAD

**Issue by ludwikbukowski** [newrelic/elixir_agent#18]
As far I see in the code, there is no support for nested segments for Transactions. Example:
```
defmodule MyMod do
  use NewRelic.Tracer

@trace :outer
def outer() do
  :timer.sleep(1000)
  inner()
end

@trace :inner
def inner() do
  :timer.sleep(1000)
  :ok
  end
end
```

The segments will be sent to NewRelic in flat namespace, i.e there will be no indication that the `inner` function is nested in `outer` part. It may lead to confusing data displayed in the `Transaction traces` in the `Trace details` tab. 

Most likely I will develop this feature in the `elixir-agent` plugin for our purposes (and maybe create PR here later on). Hence my question is:
Where can I find the documentation of REST API of the NewRelic?
I mean the API that the plugin uses for pushing transactions, segments and spans.
I believe there is a support for nested segments in NewRelic in general, so how would look like http  request ?

**Comment by binaryseed** [comment]
If we restrict the function nesting to only apply in a given process, this becomes more achievable..

**Comment by ludwikbukowski** [comment]
I understand and makes totally sense. 
Generally, the phoenix request is processed in context of one process so when we use `NewRelic.Transaction` actually we will have the structure of nested level equal to one.
Then, in this case, it'd be more informative for us, if the nesting was based on stack trace rather than processes context.

**Comment by binaryseed** [comment]
Right, but even calling out to a database will cross a process boundary

**Comment by ludwikbukowski** [comment]
As I understand, you mean following example scenario(suppose we are inside Transaction):
```
@trace :part_of_transaction
def part_of_transaction(state) do
  query = create_query(state)
  res = read_from_db(query)

@trace :read_from_db
defp read_from_db(query) do
  read_task = Task.async(fn -> DB.read_from_db(query) end)
  Task.await(read_task)
```

Here, it makes sense to measure time of `read_from_db` function since its on _critical path_ of the transaction. Time of `read_from_db` function is totally included in time of `part_of_transaction`. If we measure times spent in `DB.read_from_db` of worker spawned by `Task.async` as well (as its done now), we end up with the values that won't totally sum up to time spent in whole transaction. 
What's the value of measuring operations spent in process that's running concurrently if only time spent in the transaction matters?

Going further:
```
@trace :part_of_transaction
def part_of_transaction(state) do
  query1 = create_query1(state)
  query2 = create_query2(state)
  Process.sleep(100)
  long_async_write(query1)
  long_async_write(query2)

@trace :long_async_write
defp long_async_write(query) do
  spawn fn -> Process.sleep(5000); DB.write(query) end
```

In this case, the transaction will take only ~100 ms even though it spawns some processes that do some longer operations. 
Having current implementation, the whole transaction will be stamped with 10 secs time execution because it measures time of parallel operations. It's very confusing when displayed on graphs (Transactions -> Transaction Traces)
Additional question is what happens if the transaction process finishes before the spawned process?


If its not clear, or I don't understand your thinking, please let know!
