### ISSUE TITLE
Memory consumption while instrumenting Broadway Consumer

### ISSUE THREAD

**Issue by ethangunderson** [newrelic/elixir_agent#180]
**Describe the bug**
We're attempting to instrument a Broadway consumer and experiencing issues with memory usage.

The code looks something like this:
``` elixir
try do
  NewRelic.Transaction.Reporter.start_other_transaction(
    "Task",
    "#{unquote(inspect(module))}/perform"
  )
  do_the_work(args, job)
after
  info = Process.info(self(), [:memory, :reductions])
  NewRelic.add_attributes(
    memory_kb: info[:memory] / @kb,
    reductions: info[:reductions]
  )
  NewRelic.Transaction.Reporter.complete()
end
```

The Broadway process executes ~2-5 messages per second, so nothing too crazy. However, with this transaction in place memory usage spikes until it's fully consumed and the beam process crashes.

We've inspected the response the agent's harvester gets from sending the trace data, which I believe was {:ok, :accepted}, and we can see the transactions in Insights, but they do not appear in APM.

We've instrumented this code in other parts of the system without issue, so it definitely feels like it's related to Broadway. Any help here would be appreciated. 

**Environment**
* Elixir & Erlang version (`elixir -v`): 1.9.0-otp-22
* Agent version (`mix deps | grep new_relic_agent`): 1.16.3

**Comment by binaryseed** [comment]
I suspect that however processes are handled is interfering with the closing of the transactions causing them to merge or leak or something, how is broadway setup to execute your code?

**Comment by binaryseed** [comment]
Also Broadway uses telemetry so in the long run that is how we should instrument it (though that is a larger undertaking)

**Comment by ethangunderson** [comment]
The consumer is just part of the application's supervision tree. AFAIK we're not doing anything special there. 

Consumer config:
``` elixir
Broadway.start_link(__MODULE__,
        name: __MODULE__,
        producers: [
          sqs: [
            module: {BroadwaySQS.Producer, consumer_opts()},
            stages: 2
          ]
        ],
        processors: [
          default: [stages: 5]
        ],
        batchers: [
          default: [
            batch_size: 10,
            batch_timeout: 2000
          ]
        ]
      )
```

The code in the issue description lives in Broadway's `handle_message/3`. The opening and closing of the transaction happens within the same function.
