### ISSUE TITLE
ENV variable misspelled

### ISSUE THREAD

**Issue by kemper** [newrelic/elixir_agent#193]
I'm looking into using your new instrumentation and happened to notice in the source code that the environment variable to control ecto instrumentation is misspelled:

NEW_RELIC_ECTO_INSTRUMENTTION_ENABLED should be NEW_RELIC_ECTO_INSTRUMENTATION_ENABLED

https://github.com/newrelic/elixir_agent/blob/c25599af47306aa6a7e0e26fdce9f2b6d252bcd6/lib/new_relic/config.ex#L112

**Comment by binaryseed** [comment]
Thanks!
