### ISSUE TITLE
Databases/Ecto not instrumented 

### ISSUE THREAD

**Issue by bgroupe** [newrelic/elixir_agent#199]
**Describe the bug**
We have the agent installed in several services but one of our services does not appear to be instrumenting Ecto repos. All are configured the same way in `config.exs`, ie 

~~~elixir
config :web, Web.Endpoint, 
...
instrumenters: [NewRelic.Phoenix.Instrumenter]
...
~~~

And all of them have `telemetry` as a dependency. However with this problem service there are no data sources registered in APM whatsoever: 

![missing-data](https://content.screencast.com/users/peekcasey/folders/Jing/media/49714985-62fb-46eb-a8f4-84e6167b21d5/00000628.png)

Please advise.

**Environment**
* Elixir: 1.10.1
* Erlang: 22.2.6
* Agent version: 1.16.3

**Comment by bgroupe** [comment]
Actually figured this out: in the other services which are instrumenting properly, the Ecto repos are included in the same web endpoint application, but this problem application is an umbrella with several databases. Because of this line: 

https://github.com/newrelic/elixir_agent/blob/master/lib/new_relic/telemetry/ecto.ex#L20

Needed to add `{:new_relic_agent, "~> 1.0"}` to the deps in mix.exs of every application with an Ecto repo configured. This actually seems obvious but couldn't hurt to have an extra line in the README for clarity's sake.

**Comment by binaryseed** [comment]
This might just have to do with boot order, the agent needs to load as early as possible in the boot process to be able to detect the repos...

Is your release configured to contain all of those umbrella apps individually?

**Comment by sahilpaudel-pe** [comment]
Hi,
Can you please help me out like how to configure it to get the ecto data intrumented in the newrelic dashboard.

Thanks.

**Comment by binaryseed** [comment]
@sahilpaudel-pe There's no configuration needed - everything is automatic, if you are having trouble, please share details in a new Issue...

**Comment by bgroupe** [comment]
FWIW, My configuration was valid - my issue actually ended up being due to metric grouping issues. See: https://docs.newrelic.com/docs/agents/manage-apm-agents/troubleshooting/metric-grouping-issues
