### ISSUE TITLE
Database metric not getting instrumented in NewRelic

### ISSUE THREAD

**Issue by sahilpaudel-pe** [newrelic/elixir_agent#208]
**Describe the bug**
Unable to see database metrics in NewRelic.

My config.exs:

```
config :app, MyApp.Web.Endpoint,
  ...other config lines
  instrumenters: [NewRelic.Phoenix.Instrumenter]

config :new_relic_agent,
  app_name: "MyApp - #{Mix.env()}",
  license_key: System.get_env("NEWRELIC_LICENSE_KEY")
```
My repo.ex
```
defmodule MyApp.Repo do
  use Ecto.Repo,
    otp_app: :app,
    adapter: Ecto.Adapters.Postgres
```
My endpoint.ex

```
defmodule MyApp.Web.Endpoint do
  use Phoenix.Endpoint, otp_app: :diamond
  use NewRelic.Phoenix.Transaction
  ...other lines
```

**Environment**
* Elixir & Erlang version (`elixir -v`): **Elixir 1.7.4 (compiled with Erlang/OTP 21)**
* Agent version (`mix deps | grep new_relic_agent`): **new_relic_agent 1.10.0 (Hex package) (mix)**

**Comment by binaryseed** [comment]
Hello, Ecto support was added in agent version 1.15, you'll need to upgrade

https://github.com/newrelic/elixir_agent/blob/master/CHANGELOG.md#v1150

**Comment by sahilpaudel-pe** [comment]
Thanks Vince for the resolution,
I can add the latest version instead of 1.15 works right like v1.17.1?

**Comment by binaryseed** [comment]
yes!

**Comment by sahilpaudel-pe** [comment]
@binaryseed This might be a stupid question but I wanted to know if there is anyway I can use with elixir v1.7

**Comment by binaryseed** [comment]
The agent has a hard requirement on OTP 21+, and is tested in the last 2 versions of Elixir
