### ISSUE TITLE
How to make the trace more detailed?

### ISSUE THREAD

**Issue by VitorTrin** [newrelic/elixir_agent#226]
I've recently introduced this agent to my application. I use the phoenix instumentation and a handmade instrumentation for requests that aren't web related.

I've come to the issue that the trace shows the controller, the external requests and the database, and that would be plenty, if only the request didn't spend most of it's time doing something else that isn't labeled and probably is just elixir code.

Can i do something to help label more? Is this an issue that must be raised with the product and not with this lib?

**Comment by binaryseed** [comment]
This is a matter of instrumentation, you can instrument your own functions with `NewRelic.Tracer`, or if there's another open source library with it's own built-in telemetry instrumentation, that can be considered for adding to the agent itself

**Comment by VitorTrin** [comment]
Do I need to anotate every function that I want to show in my trace, or only the first one?
I added trace to one of my controllers, it's traces don't appear any different from traces of the the others.

**Comment by binaryseed** [comment]
Here's the docs: https://hexdocs.pm/new_relic_agent/NewRelic.Tracer.html

**Comment by VitorTrin** [comment]
I didn't found the docs to be helpful, as I had already read and re read them before asking here.

**Comment by VitorTrin** [comment]
Ok, after a lot of guessing, I understand the problem. The Phoenix instumentation automatically traces all the controllers, so adding manual tracing to the controler did nothing.
