### ISSUE TITLE
Compilation error on rewrite_call_term

### ISSUE THREAD

**Issue by VitorTrin** [newrelic/elixir_agent#227]
If you attempt to trace a function that has some kinds of match, it fails to compile.
The following function reproduces the error :

```elixir
@trace :not_pointless
def not_pointless(nil = _ignored), do: nil
```
It appears that for tracing purposes none of the sides of the match are variables

**Environment**
Elixir 1.9.4 OTP22
agent in 1.8.1

**Comment by binaryseed** [comment]
Thanks for the report! I'll look into a fix...

Can I ask why you are assigning a literal to an unbound variable?

**Comment by binaryseed** [comment]
Fix in #228

**Comment by VitorTrin** [comment]
I have a function with five or more parameters, and it's made of dozens of defs with pattern matches. To be more clear on what we are matching, we always assign to a variable all parameters even when we don't use them.

**Comment by binaryseed** [comment]
Gotcha, so it's a form of documentation - thanks!
