### ISSUE TITLE
Trace all fuctions in a module with a single attribute

### ISSUE THREAD

**Issue by VitorTrin** [newrelic/elixir_agent#231]
**Is your feature request related to a problem? Please describe.**
When adding tracing to a big codebase, I found adding `@trace` to every function I want to trace tedious and prone to missing some functions due to human error as it's very repetitive. If I want to trace a function in a module, chances are I also want to trace all the other functions in this module as it is a domain module.

**Describe the solution you'd like**
It would be very helpfull if there were an atribute that enabled tracing for all the functions in a module. Here are some examples of how it could be used

```elixir
use NewRelic.Tracer
@trace_all
```
or

```elixir
use NewRelic.Tracer, trace_all?: true
```

Here's an attempt I made. https://github.com/VitorTrin/elixir_agent/commit/295ce113072b647d49905896db4aec0e4f37c3c8. I got stuck in how to make the mfa be `"TracerTest.CompletelyTraced.fun/0"` instead of `"TracerTest.CompletelyTraced.fun:true/0"`

If possible, it would also be nice if we could choose between tracing all functions and only the public ones.

```elixir
use NewRelic.Tracer
@trace_all :only_public
# @trace_all true
```
or

```elixir
use NewRelic.Tracer, trace_all?: public
# use NewRelic.Tracer, trace_all?: true
```

**Describe alternatives you've considered**
I use an ugly hack were I define a on_definition hook that inserts the trace attribute for all functions and happens before the on_definition hook that `NewRelic.Tracer` uses

**Comment by binaryseed** [comment]
Hi, thanks for this suggestion!

I'm a little hesitant to add this feature. I understand that it takes manual effort to trace each function, but what that does offer is something that is explicit and can't done by accident. Tracing a function incurs a small but meaningful impact on the performance of a function.

Additionally.. 1) There's more than one tracer type - for example, functions that are intended to track an External call are traced with a different annotation than basic function tracers. 2) Function heads can be labeled with a name that is different from the function name to identify individual function heads, which would also be missing. I imagine if there was a `trace_all`, folks would eventually still need those additional features, which means adding in additional tracers which would further increase the complexity of the system...

**Comment by mattbaker** [comment]
I'd also be worried about accidentally tracing a function that relied on tail call optimization to not blow the stack.

**Comment by VitorTrin** [comment]
If you want something that isn't supported by trace_all, go remove the one line that enables it and go add all those traces.
Right now  I have to commit to the time demanding solution even for basic stuff.
Also, there's nothing right now preventing you from adding trace to a tail call optimized function, only documentation.

**Comment by VitorTrin** [comment]
I had the deliberate and manual experience with external calls.
With all the copy, paste and minor changes that I had to do that was by far the most buggy of all the tracing I did, and please understand the other tracing I'm comparing was hacking and calling undocumented functions and macros. (I'm only talking about manual tracing, the automated tracing this lib gave me was easy and delightful)

**Comment by binaryseed** [comment]
How many trace annotations are you dealing with in your application?

**Comment by VitorTrin** [comment]
I've only starting, so around 15 regular traces in 2 modules right now, but if I decided to trace the entire domain it could reach something close to a hundred. I traced 37 external calls in 11 different modules. And that is only for 1 application, I maintain at least 4 different applications, and there are more elixir aplications in my company.

**Comment by VitorTrin** [comment]
Oh, and I forgot to mention all the jobs. I used a custom module for that also, created by another team, that would be another 40 anotations.

**Comment by binaryseed** [comment]
Can you share the macro you're using to do this? perhaps we can get that into good shape.

I talked with some other agent teams - this feature doesn't exist in any of the other language agents, and folks tend to agree that the risk / reward balance is a bit skewed towards risk.

**Comment by VitorTrin** [comment]
Not my most proud code, but it works.
```elixir
defmodule NewRelic.ModuleTracer do
  defmacro __using__(trace_private?: trace_private) do
    if trace_private do
      quote do
        # Yes, this is the right order. The latest @on_definition happens first
        # No, I didn't knew this before
        use NewRelic.Tracer
        @on_definition {NewRelic.ModuleTracer, :all}
      end
    else
      quote do
        use NewRelic.Tracer
        @on_definition {NewRelic.ModuleTracer, :only_public}
      end
    end
  end

  def all(%{module: module}, _access, name, _args, _guards, _body) do
    # The lib only traces if this atribute is set, and it removes it after every
    # definition. If we want to trace every call we make, we just need to set it
    # before they do their __on_definition__
    Module.put_attribute(module, :trace, name)
  end

  def only_public(%{module: module}, :def, name, _args, _guards, _body) do
    Module.put_attribute(module, :trace, name)
  end

  def only_public(_env, _access, _name, _args, _guards, _body) do
    nil
  end
end
```

**Comment by binaryseed** [comment]
Thanks, I'm going to close this. I don't think it's something we want to add in the agent, but I'm glad you found a work-around for yourself & others!
