### ISSUE TITLE
Distributed trace for generic (not http) requests

### ISSUE THREAD

**Issue by VitorTrin** [newrelic/elixir_agent#233]
**Is your feature request related to a problem? Please describe.**

Distributed trace works great for http requests, but there is no (clean) way to make it work when the request isn't related to http.

**Describe the solution you'd like**

A function that creates a serialized context, most likely `DistributedTrace.distributed_trace_headers(:generic)`, and a function that takes a serialized context and adds to the current transaction, akin to  `DistributedTrace.track_transaction(context, transport_type: transport_type)` but that accepts the serialized context.

**Describe alternatives you've considered**

The current workaround is to call `DistributedTrace.distributed_trace_headers(:http)`, make them serializeble on our own, add to the request, and the other side takes the serialized headers, builds a conn, adds the headers and calls `W3CTraceContext.extract()` to get a built context.

**Comment by binaryseed** [comment]
Duplicate: https://github.com/newrelic/elixir_agent/issues/265
