### ISSUE TITLE
Compilation error with enforced key

### ISSUE THREAD

**Issue by VitorTrin** [newrelic/elixir_agent#236]
**Describe the bug**
It seems to be a corner case of the previous enforced keys problem. The problem seem to arise when you match some of the keys but not all required ones

How to reproduce:

```elixir
  defmodule Traced do
    use NewRelic.Tracer
    @enforce_keys [:key, :second_key]
    defstruct [:key, :second_key]

    @trace :mod
    def mod(%Traced{key: val}), do: val
  end
```

**Comment by binaryseed** [comment]
Hi there! I took a look, but I can't reproduce this with the code provided, could you submit a PR with code changes that cause the problem you are seeing?

**Comment by binaryseed** [comment]
Fix in https://github.com/newrelic/elixir_agent/pull/239
