### ISSUE TITLE
sample_process logging less data

### ISSUE THREAD

**Issue by spencerdcarlson** [newrelic/elixir_agent#244]
**Describe the bug**
I noticed that [NewRelic.sample_process/0](https://hexdocs.pm/new_relic_agent/NewRelic.html#sample_process/0) started returning a lot less data after updating > 1.18.0

The app above (singularity) is using `:new_relic_agent, "1.18.0", "a53cfd9fa490b9dcab479743c359fbfc8bfe1045a20f63a68d66c4f08700b01a"`

The app below (connector gate) is using `:new_relic_agent, "1.18.5", "9fe6374b3713cf20a0bf6dec409da41acfa3a0f1248b2f3abe5d020d12ecf1d6"`

<img width="840" alt="Screen Shot 2020-06-23 at 10 02 20 AM" src="https://user-images.githubusercontent.com/1206303/85427200-ab99c980-b538-11ea-8035-9f15e7f96ac5.png">

Both are doing comparable work. I noticed the drop in data points after updating the new relic agent in the second application. 

Both are running the same query with different appIds
```SQL
SELECT 
  max(memory_kb) 
FROM ElixirSample 
WHERE 
  appId = 305400675 AND 
  name LIKE 'PdmMetrics.%' 
TIMESERIES FACET name, host
```

**Comment by binaryseed** [comment]
Hi there, would you mind sending an email to vince at newrelic with links to your app so I can take a look?

**Comment by binaryseed** [comment]
After looking at this, I believe that this itself is a sampling issue. There are only a fixed number of events that can be sent.

In the future, I'll be migrating these stats to metrics now that metrics can easily be dashboarded with NRQL...

https://github.com/newrelic/elixir_agent/projects/3#card-35511671
