### ISSUE TITLE
Ability to ignore specific errors

### ISSUE THREAD

**Issue by vsouza** [newrelic/elixir_agent#245]
**Is your feature request related to a problem? Please describe.**
Other agents have support to specify which class or which module we can trace or ignore errors. For example, my application uses a simples `raise ResourceNotFound` and it will results in HTTP 404 for the client, because we catch this before sending any answer. But at looking at my error rate in APM doesn't reflect real error rate, considering all raises by my app.

According to this documentation [link](https://docs.newrelic.com/docs/agents/manage-apm-agents/agent-data/manage-errors-apm-collect-ignore-or-mark-expected) It's possible to ignore certain errors in other agents. Can we provide something like this for Elixir Agent?

**Describe the solution you'd like**
Provide a config option with a list of errors to ignore

**Describe alternatives you've considered**
An option in @trace method, with some kind of `ignore_exception: MyCustomException`

Thanks.

**Comment by binaryseed** [comment]
The agent does have the ability to set an exception as `expected` which won't influence the error rate... it's demonstrated in this test: 

https://github.com/newrelic/elixir_agent/blob/45a067c6e53c157f728fd6b06b534a02a997ef5a/test/metric_error_test.exs#L5-L7

https://github.com/newrelic/elixir_agent/blob/45a067c6e53c157f728fd6b06b534a02a997ef5a/test/metric_error_test.exs#L28

**Comment by vsouza** [comment]
Amazing! Works like a charm

**Comment by binaryseed** [comment]
Great! I've taken a note to document that :)
