### ISSUE TITLE
On k8s deploy `preconnect failed_request` (keep disconnected from new relic) 

### ISSUE THREAD

**Issue by danielcaro** [newrelic/elixir_agent#247]
**Describe the bug**

I`m using preemptible node (it is restarted at least once a day).  When the node restart, isn't connecting again.  I must stop and restart the container to done connection with new relic.  This started when I updated to elixir 1.10.  The agent implements a connection retry policy ?

```
cat ./tmp/new_relic.log
[INFO] - 2020-07-05 12:50:33 - Log File: ./tmp/new_relic.log
[INFO] - 2020-07-05 12:50:33 - Detected Ecto Repo `Persistence.Repo`
[ERROR] - 2020-07-05 12:50:38 - preconnect: (failed_request) {:failed_connect, [{:to_address, {'collector.newrelic.com', 443}}, {:inet, [:inet], :timeout}]}
```

After manual restart
```
[INFO] - 2020-07-05 18:16:21 - Log File: ./tmp/new_relic.log
[INFO] - 2020-07-05 18:16:21 - Detected Ecto Repo `Persistence.Repo`
[INFO] - 2020-07-05 18:16:21 - Reporting to: https://rpm.newrelic.com/accounts/XXXXX/applications/XXXXX
[DEBUG] - 2020-07-05 18:16:26 - Completed Error Event harvest - size: 0
[DEBUG] - 2020-07-05 18:16:26 - Completed Transaction Event harvest - size: 0
[DEBUG] - 2020-07-05 18:16:26 - Completed Custom Event harvest - size: 5
[DEBUG] - 2020-07-05 18:16:31 - Completed Transaction Event harvest - size: 0
```

**Environment**
* GKE docker image `elixir:1.10.3`
* `Erlang/OTP 22 [erts-10.7.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]`
* `Elixir 1.10.3 (compiled with Erlang/OTP 22)`
* Deployed with `distillery 2.1.1`
* `new_relic_agent 1.19.2`
* `new_relic_phoenix 0.2.1`
* `cowboy 2.8.0`

Sorry about my english ( first time opening an issue) .

**Comment by binaryseed** [comment]
Hi there, is there perhaps something about the network / restart process that would prevent the node from being able to make an HTTP request when it is restarted?

**Comment by danielcaro** [comment]
yeah! , @binaryseed , good point! after search a lot, I found thath GKE has an issue of nxdomain when node restart.

No one of solution proposed on GKE and K8S forum works until now, but looks it a weird behavior with dns on k8s .  

Thanks !!
 
PS:  Should I close the issue ??

**Comment by binaryseed** [comment]
Yeah, i'll close it - any indication how long the issue lasts? curious how long we'd have to retry for it to work (we do retry in the agent already)
