### ISSUE TITLE
Missing route name in the dashboard

### ISSUE THREAD

**Issue by akash-akya** [newrelic/elixir_agent#248]
We have a custom generic plug which handles specific path (`/metrics`) for all applications. We are not seeing proper metrics for this route.

What we are seeing:
![Screenshot 2020-07-06 at 11 33 33 AM](https://user-images.githubusercontent.com/9396022/86561103-7bf9b100-bf7d-11ea-80c3-9cf7eb2f13bb.png)

**Expected:** 
`/GET//metrics`

**When we click on this transaction:**
![Screenshot 2020-07-06 at 11 33 56 AM](https://user-images.githubusercontent.com/9396022/86561106-7ef4a180-bf7d-11ea-8898-14ec4e793c97.png)

this plug is defined something like
```elixir
defmodule Core.Api.Metrics do
  @behaviour Plug

  alias Plug.Conn

  def init([]), do: []

  def call(%Plug.Conn{path_info: ["metrics"]} = conn, _opts) do
    conn
    ....
    ....
    |> Conn.send_resp(200, ....)
    |> Conn.halt()
  end

  def call(conn, _opts), do: conn
end

```

From cursory look, elixir_agnet is getting path information from a private field `conn.private[:plug_route]` set by `Plug.Router`. Since In this case path is not defined by router, `conn.private[:plug_route]` won't be set.

Maybe accept path name from a custom  assign or private field like `:new_relic_route` and fallback to `conn.private[:plug_route]` if that does not exist 

**Environment**
* Elixir & Erlang version (`elixir -v`):
```text
Erlang/OTP 22 [erts-10.6] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.8.2 (compiled with Erlang/OTP 22)
```
* Agent version (`mix deps | grep new_relic_agent`):
```
new_relic_agent 1.18.4
```
tried with latest and the issue still exists

**Comment by binaryseed** [comment]
Hi there! You can manually set the "transaction name" to accomplish what you want:

https://hexdocs.pm/new_relic_agent/NewRelic.html#set_transaction_name/1
