### ISSUE TITLE
Add ability to link process to parent transaction/trace

### ISSUE THREAD

**Issue by ananthakumaran** [newrelic/elixir_agent#249]
**Is your feature request related to a problem? Please describe.**

```elixir
parent = self()
Cache.get(key, fn ->
  spawn_link(fn ->
    # fetch resource a  
  end)
  spawn_link(fn ->
    # fetch resource b
  end)

  build_value()
end)
```
In the above example, the `Cache.get` sends a message to gen server and the processing happens on a different process (inside genserver handle_call). At this point, the tracking is lost, which is ok as this would be a fast operation. In case the key is not in the cache, the fallback function will get executed and this function may in turn spawn new processes to fetch resources via HTTP or other protocol. Currently, there is no way to link the processes back to the parent transaction/trace. 

**Describe the solution you'd like**

It would be great if the agent exposes an API to link the spawned process to the parent transaction/trace so we can do

```elixir
parent = self()
Cache.get(key, fn ->
  spawn_link(fn ->
    NewRelic.link(parent, self())
    # fetch resource a  
  end)
  spawn_link(fn ->
    NewRelic.link(parent, self())
    # fetch resource b
  end)

  build_value()
end)
```

**Describe alternatives you've considered**
I can't find any alternative other than calling non public API which might break on any upgrade.

**Comment by binaryseed** [comment]
Hello there! The agent already does this work for you by using OTP's `erlang:trace`..

The low-level `spawn_link` doesn't support the trace messages though.

If you use OTP's `proc_lib:spawn_link`, the process will in fact get linked up by the agent as expected...

**Comment by ananthakumaran** [comment]
To be clear, the fallback function is called from inside the `handle_call` of gen server, so the context is already lost at this point. You can see from the sample below. Even if I switch the spawn_link to proc_lib, it's not going to work because the context is already lost at this point.

```elixir
IO.inspect({self(), NewRelic.DistributedTrace.get_tracing_context()})
Cache.get(key, fn ->
  IO.inspect({self(), NewRelic.DistributedTrace.get_tracing_context()})
end)
```

```
{#PID<0.1354.0>,
 %NewRelic.DistributedTrace.Context{
   guid: "44039d15707eb616",
   type: "App",
   ....
 }}
{#PID<0.1355.0>, nil}
```

**Comment by binaryseed** [comment]
What does `Cache.get` do with the `fn` that it's passed?

**Comment by ananthakumaran** [comment]
This is the standard interface that's exposed by most of the inmemory cache library

[cache_tab](https://github.com/processone/cache_tab)
```
cache_tab:lookup(tab_name, <<"key">>, fun() -> read_value_if_not_cached() end).
```

[cachex](https://hexdocs.pm/cachex/Cachex.html#fetch/4)
```
Cachex.fetch(:my_cache, "key", fn(key) ->
  { :commit, String.reverse(key) }
end)
```

if the data for the key is available, it will return the value, otherwise it will invoke the `fn`, persist the data and return the value. Depending on the library, the `fn` will get invoked from a different process. Both cachex and cache_tab invoke it from different process, not the process where the fetch/get call happens.

**Comment by binaryseed** [comment]
Ok, so when the function is passed to a different process that the link isn't known since we don't track through message passing.

The trouble is that in that case we need to also make sure that there's an `unlink` that happens so that the Transaction doesn't include work done by the next message passed to the Cache process.

It's further complicated by the fact that a process can exit at any point, so we'd also need to monitor for exits.

That's generally why tracing doesn't follow & include functions called through message passing

**Comment by ananthakumaran** [comment]
I understand the concern here about tracking the Genserver process that will be shared by multiple transactions. If you look at my first example, I am planning to track only the process that's **spawned** inside the fallback. This will be exclusively used for the parent transaction and will also exit before the parent transaction finishes.

Currently, we follow this inmemory cache pattern for some of the API resources, and those resource fetch calls never get attributed to the correct transaction/trace.

**Comment by binaryseed** [comment]
I get that your example use case is contained to spawned process, but an API function like this could easily be used in cases where that's not the case.

I'll have to think a little more about how to help you achieve what you are asking for here...
