### ISSUE TITLE
Support custom environment variables for agent configuration

### ISSUE THREAD

**Issue by jared-mackey** [newrelic/elixir_agent#257]
**Is your feature request related to a problem? Please describe.**
There should be a way to configure the agent with custom environment variables. 

**Describe the solution you'd like**
Being able to set the license key with `{:system, "SECRET_NEW_RELIC_LICENSE_KEY"}`

**Describe alternatives you've considered**
Able to set it at runtime is another option. We make heavy use of Confex in our app but I'm unsure of when the agent configuration is loaded.

**Comment by jared-mackey** [comment]
Happy to do a PR to implement the proposed solution but wanted to get feedback from the author first.

**Comment by binaryseed** [comment]
We chatted about this and found that it won't be necessary, the existing env var config will work with a little layer of indirection when booting, setting the agent env var based on the value of a custom env var...
