### ISSUE TITLE
High CPU usage when many subprocesses are spawned from a Phoenix controller

### ISSUE THREAD

**Issue by benizi** [newrelic/elixir_agent#259]
**Describe the bug**
New Relic processing takes a lot of CPU + memory when many subprocesses are spawned from a Phoenix controller.

**Environment**
* Elixir & Erlang version (`elixir -v`):
  ```
  Erlang/OTP 22 [erts-10.7.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

  Elixir 1.10.4 (compiled with Erlang/OTP 22)
  ```
* Agent version (`mix deps | grep new_relic_agent`):
  ```
  * new_relic_agent 1.19.4 (Hex package) (mix)
    locked at 1.19.4 (new_relic_agent) 03bd88cd
  ```

**Details**
Attaching a tarball of a Phoenix app that demonstrates the problem.
[nrr.tar.gz](https://github.com/newrelic/elixir_agent/files/5152618/nrr.tar.gz)

To run, use either Docker or the raw app:
- raw app
  ```sh
  tar zxv < nrr.tar.gz
  NEW_RELIC_APP_NAME='Your app here' NEW_RELIC_LICENSE_KEY=xyz123 mix phx.server
  ```
- Docker
  ```sh
  docker build -t nr-test - < nrr.tar.gz
  docker run --rm -i -t -p 4000:4000 -e NEW_RELIC_APP_NAME='Your app here' -e NEW_RELIC_LICENSE_KEY=xyz123 nr-test
  ```

In both cases, if either `NEW_RELIC_` variable is missing, `:new_relic_agent` and `:new_relic_phoenix` are completely disabled (OTP apps don't even get loaded).

Test endpoint `/api/many/:n` (e.g., `curl localhost:4000/api/many/10000`) spawns `n` processes, each of which sleeps for 500ms (but does no other work). Params:

Name | Default | Description
:-- | :-- | :--
`n` | in path | (required) number of processes to spawn
`sleep` | 500 | number of ms to sleep in each subtask
`task_wait` | 30,000 | max number of ms to wait for each task
`overall_wait` | 30,000 | max number of ms to wait for all tasks

On my laptop, I get these results:

With New Relic disabled, these both complete successfully with no noticeable spike in CPU usage afterward:
- `/api/many/100000` returns in ~1.2s
- `/api/many/1000000` returns in ~11.8s

With New Relic enabled:
- `/api/many/100000` returns in less than 2s, but one CPU remains pegged for at least a few minutes (3+ min of ~100% CPU in htop)
- `/api/many/1000000` returns in ~23s, but two CPUs are pegged for ~1min, and another remains pegged for a while (10+ min)

**Comment by benizi** [comment]
(Not getting high memory usage w/ the repro app, but that's what caused us to find it in the first place -- actual app crashing due to OOM when New Relic agent is enabled.)

**Comment by binaryseed** [comment]
Hi! thanks for the repro steps. I've been looking at this kind of situation and will take a look soon!

**Comment by benizi** [comment]
> (Not getting high memory usage w/ the repro app, but that's what caused us to find it in the first place -- actual app crashing due to OOM when New Relic agent is enabled.)

Scratch that -- wasn't getting noticeably-high memory usage, but it's using quite a bit:

- With New Relic agent disabled, clamping to 2GiB in Docker (adding flags: `--memory 2g --memory-swap 2g`) is sufficient to allow `/api/many/1000000` to complete.
- With the agent enabled...
  - ... using `4g`, the process is killed before sending a response.
  - ... with `6g`, `:os_mon` warns before it returns successfully.
