### ISSUE TITLE
Support for high security mode 

### ISSUE THREAD

**Issue by codebender** [newrelic/elixir_agent#260]
Hi!
I was looking through the code base for "high security mode" but I don't think I found anything.

Is there a reason this agent doesn't support high security mode like your other agents?

**Comment by binaryseed** [comment]
This agent is released as open-source, which means it doesn't support everything New Relic as a whole supports.

That said, you can turn off security sensitive data collection including error tracing and query collection:

https://hexdocs.pm/new_relic_agent/NewRelic.Config.html#feature?/1-security
