### ISSUE TITLE
No data being reported by agent

### ISSUE THREAD

**Issue by dfalling** [newrelic/elixir_agent#262]
Hi, I may just be misunderstanding the README, but I'm not getting anything reported into New Relic.

**Elixir Config**
On the Elixir side, all I've done is installed this agent, and added the following to my config:
```elixir
config :new_relic_agent,
  app_name: "Ido",
  license_key: System.get_env("NEW_RELIC_LICENSE_KEY")
```

I'm using Ecto and Redix, so I _think_ they should be showing up automatically via telemetry.  I'm using Phoenix 1.5 so sadly I can't get any metrics out of that.

**New Relic Config**
In New Relic I haven't done anything aside from sign up for an account and copy the license key over to my environment.

**Environment**
Erlang/OTP 22 [erts-10.4.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
Elixir 1.10.0 (compiled with Erlang/OTP 21)
* new_relic_agent 1.19.4 (Hex package) (mix)
  locked at 1.19.4 (new_relic_agent) 03bd88cd

I haven't seen any data come into New Relic from my app, and no errors in my log.  Have I missed a step in the config?  Thanks!

**Comment by binaryseed** [comment]
How do you deploy / run your app? `System.get_env` as you've shared it is run at compile time...

If you set the `NEW_RELIC_LICENSE_KEY` env var, you don't need to also specify it in Application config, the agent knows how to pick it up...

**Comment by dfalling** [comment]
I use Distillery to deploy and am using System.get_env for other config variables as well.  I did remove it now though and still don't see any data in New Relic.

**Comment by binaryseed** [comment]
Do you seen anything in the logs? (by default all New Relic agents log to `tmp/newrelic.log`, but it can be configured easily with `config :new_relic_agent, log: "stdout"`)

**Comment by dfalling** [comment]
Ah, toggling that on and tailing the logs on my box, I see a ton of these:
```
2020-09-08T03:10:19.859058+00:00 ido-api[ido-api-7d8d9789fb-lpdk7]: web.1  | [DEBUG] - 2020-09-08 03:10:19 - Completed Custom Event harvest - size: 0
2020-09-08T03:10:24.816418+00:00 ido-api[ido-api-7d8d9789fb-lpdk7]: web.1  | [DEBUG] - 2020-09-08 03:10:24 - Completed Error Event harvest - size: 0
2020-09-08T03:10:24.857842+00:00 ido-api[ido-api-7d8d9789fb-lpdk7]: web.1  | [DEBUG] - 2020-09-08 03:10:24 - Completed Transaction Event harvest - size: 0
2020-09-08T03:10:24.860927+00:00 ido-api[ido-api-7d8d9789fb-lpdk7]: web.1  | [DEBUG] - 2020-09-08 03:10:24 - Completed Custom Event harvest - size: 10
```

**Comment by binaryseed** [comment]
Yep, that's data getting reported! Perhaps you didn't instrument your Plug pipeline, it's not automatic (yet)

**Comment by dfalling** [comment]
Aah, I was on the usage summary page but the data still isn't showing up there.  But I went to Entity Explorer and it has started to come in there.  Thanks!
