### ISSUE TITLE
reporting bug issues 

### ISSUE THREAD

**Issue by katekordnejad** [newrelic/elixir_agent#279]
two separate issues with the NewRelic agent for elixir:1. When attempting to monitor functions in our Broadway jobs, we begin to see the NewRelic agent fail to complete all traces. Many traces do complete, but others are left open. With the rate of throughput, this quickly balloons memory to ~13GB, making the BEAM unresponsive.2. Ecto Telemetry raises UnsupportedEctoAdapter, even though we're using Postgrex. Oddly, we get reporting for a short time before this occurs.

**Comment by binaryseed** [comment]
This looks like a duplicate of #280
