### ISSUE TITLE
Crash in os_mon's cpu_sup during BEAM shutdown

### ISSUE THREAD

**Issue by tomtaylor** [newrelic/elixir_agent#286]
We just integrated the New Relic agent, and weren't using `os_mon` previously. During our deploys, we send SIGTERM to shutdown our BEAM process, which triggers the application shutdown sequence.

In the moments after SIGTERM is fired I sometimes see the following log line:

```
Process #PID<0.5942.0> on node :"poplar@b89fef50-49bc-46ed-a15c-7f14e58f8147" raised an exception
** (ArgumentError) argument error
 :erlang.port_command(#Port<0.14>, 'u')
 (os_mon 2.6.1) cpu_sup.erl:597: :cpu_sup.port_server_loop/2
```

It looks like `cpu_sup` is crashing during [`:cpu_sup.util()`](https://github.com/newrelic/elixir_agent/blob/master/lib/new_relic/sampler/beam.ex#L80) because the port is no longer running. I suspect this might be because `os_mon` is shutting down before the BEAM sampler process, although I'm not sure.

I can disable `cpu_sup`, but now I get `OS_MON (:cpu_sup) called by #PID<0.6139.0>, unavailable` every 5 seconds!

**Environment**

Elixir: 1.11.1
Erlang: 23.1.1
Agent: 1.22.0

**Comment by binaryseed** [comment]
This should be cleared up via #287

**Comment by binaryseed** [comment]
Thanks!

**Comment by binaryseed** [comment]
Fixed in `1.22.1`

**Comment by tomtaylor** [comment]
So I think we got to the bottom of this!

`cpu_sup` is a Port, running as a subprocess of BEAM. We run on Heroku, and when Heroku shutsdown a dyno, it fires SIGTERM to all the processes, not just the top of the process tree. For us, that's BEAM, but also the `cpu_sup` child process, which shuts down immediately.

While the rest of BEAM is shutting down each application in sequence the New Relic BEAM Sampler process polls `:cpu_sup.util()`, the `cpu_sup` GenServer blows up with ArgumentError because the `cpu_sup` Port is no longer available. I don't believe this ArgumentError makes its way back to the BEAM Sampler process because it's not linked, so I don't think this fix will solve the problem for us.

I'm not sure how we can prevent `cpu_sup` from catching the SIGTERM that Heroku produces, so I think we might have to just ignore this exception in our exception tracking system for the moment.

Adding safe_check around `:cpu_sup.util()` is probably a wise thing to do anyway.

Thanks for your help!

**Comment by binaryseed** [comment]
I'd recommend you raise this bug in Erlang/OTP.. their issue tracker is: https://bugs.erlang.org/issues/?jql=

**Comment by tomtaylor** [comment]
I thought about it, but I'm not convinced the subprocess is doing anything wrong. If the process became detached, being able to exit it with SIGTERM seems like a normal thing to do. That said, I don't know whether there are expectations around signals that ports should/shouldn't respond to. What do you think?

**Comment by binaryseed** [comment]
Seems like a bug to me, it's worth at least opening an issue

**Comment by tomtaylor** [comment]
👍 I've filed https://bugs.erlang.org/projects/ERL/issues/ERL-1392
