### ISSUE TITLE
Support for incrementing counters

### ISSUE THREAD

**Issue by tomtaylor** [newrelic/elixir_agent#291]
Unlike the Ruby agent, I couldn't see a function for sending an incrementing counter. I'm looking for the Elixir equivalent of [this](https://docs.newrelic.com/docs/agents/ruby-agent/api-guides/ruby-custom-metrics#increment_metric).

It would be great to add this, if it doesn't exist.

**Comment by binaryseed** [comment]
Hello there! This can be accomplished with `NewRelic.report_custom_metric("My/Metric", 1)` as metrics are accumulated and aggregated during the "harvest" period
