### ISSUE TITLE
Unable to disabled harvester via config

### ISSUE THREAD

**Issue by krankin** [newrelic/elixir_agent#293]
**Describe the bug**
Setting `harvester_enabled` to `false` in config does not disable the harvester. 

It appears to me the issue is in [NewRelic.Init.determine_config#2](https://github.com/newrelic/elixir_agent/blob/4e95713d9f4ca104a146fe8729feff47deca2016/lib/new_relic/init.ex#L82)

If `determine_config#1` returns false, it is taking the default option, which for the harvester is `true`. 

This would impact any configuration values where the options are falsey. 

Here's a sample failing test (requires exposing `Config.harvest_enabled?`)

```elixir
    Application.put_env(:new_relic_agent, :harvest_enabled, false)
    NewRelic.Init.init_config()
      
    refute NewRelic.Config.harvest_enabled?  #Should be false, but is true
```

I'd be happy to submit a PR to change this to look for an actual false value before doing the default value. 

**Environment**
* Elixir & Erlang version (`elixir -v`):
```
Erlang/OTP 23 [erts-11.1.1] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [hipe]

Elixir 1.11.1 (compiled with Erlang/OTP 23)
```
* Agent version (`mix deps | grep new_relic_agent`):
```
new_relic_agent 1.22.3 (Hex package) (mix)
locked at 1.22.3 (new_relic_agent) 8df3db90
```

**Comment by binaryseed** [comment]
Looks like you are correct, we should be doing it more like `determine_feature` does with the default. PR & that test welcome!
