### ISSUE TITLE
Ecto/Database Queries are not available on NewRelic Dashboard

### ISSUE THREAD

**Issue by techgaun** [newrelic/elixir_agent#297]
**Describe the bug**
I am having a specific problem on the production application where it does not show any database operations under `Databases` view. When I query raw data on `apm.service.datastore.operation.duration` under `Metric`, I do not see any data either.
```sql
SELECT average(`apm.service.datastore.operation.duration`) FROM Metric WHERE appName LIKE '%' AND `entity.guid` = 'MyEntityGuid' SINCE 30 MINUTES AGO TIMESERIES
```
I can see that the transaction traces do have associated database traces though.

The strange thing is the same application under another environment is reporting all the ecto queries with all the necessary details. The configurations for newrelic agent are identical on both environment and I've verified them multiple times. The difference is in the load and the production application handles roughly 100x more traffic per minute.

If I check the newrelic agent log, I can see the telemetry event kicks right, is handled and has the log:

```
Detected Ecto Repo `MyApp.Repo`
```

In the log, I've also verified it is reporting to the right application. Everything else looks great, only ecto integration is not working.

Worth noting, the metric for Redix is also available on the other test environment, Production does not have any data around Redix too.

**Environment**
* Elixir & Erlang version (`elixir -v`): 1.8.2 / 21.3.8
* Agent version (`mix deps | grep new_relic_agent`): 1.22.3

![newrelic](https://user-images.githubusercontent.com/1886670/104852452-bb0ba600-58c0-11eb-8b9d-1fde6e72063f.png)
![newrelic-transaction](https://user-images.githubusercontent.com/1886670/104852555-5270f900-58c1-11eb-863a-07ce458ece28.png)

**Comment by binaryseed** [comment]
Hi there, could you send me an email vince at newrelic, and we can look a bit closer at the data that is reporting? We can re-open this if we find an issue that needs fixing.

**Comment by techgaun** [comment]
Sent an e-mail, thanks @binaryseed

**Comment by lorenzomar** [comment]
Hello, I'm having same issue. 

This is my current configuration:
```
Erlang/OTP: 26
Elixir: 1.14.5
newrelic/elixir_agent: 1.27.8
```

In agent log is present the row: `[INFO] - 2023-07-06 14:20:17 - Detected Ecto Repo App.Repo`

Nothing appear on NewRelic.
