### ISSUE TITLE
Very high memory usage for transaction with lots of database calls

### ISSUE THREAD

**Issue by tomtaylor** [newrelic/elixir_agent#308]
**Describe the bug**

We're running a background job that makes 100,000s of Postgres calls inside a single process. In doing so, memory usage of the `NewRelic.Transaction.Reporter.Collecting` ETS table climbs to hundreds of megabytes, causing us to hit the memory usage limit on our Heroku dyno.

It looks like the table is filling with each individual Postgres database call, and isn't being flushed. I've attached a couple of screenshots early in the process, before we get out of memory issues.

**Environment**

* Elixir & Erlang version (`elixir -v`): `Elixir 1.11.2 (compiled with Erlang/OTP 23)`
* Agent version (`mix deps | grep new_relic_agent`): `1.23.0`

![image (1)](https://user-images.githubusercontent.com/565/107675344-eac78700-6c8f-11eb-9768-016626bff6a5.png)

![image (2)](https://user-images.githubusercontent.com/565/107675340-ea2ef080-6c8f-11eb-9e49-39ae608d5cf3.png)

**Comment by binaryseed** [comment]
Hi there. While I'm sure there are some optimizations we can manage here, I have a few questions...

How long does the overall Transaction take? There's a warning about long running transactions and memory usage

What behavior would you expect to see in the case like this?

**Comment by tomtaylor** [comment]
Hi there, it’s quite a long running process - about 15 mins at the moment.

I don’t think I’ve seen a warning about long running processes - can yyou point me to it?

I’m not sure what I’d expect the behaviour to be here. I think it should probably follow the principle of least surprise and discovering a large amount of memory usage in the ETS table did take us a bit of digging around.

Options that might make sense:

- Stopping counting after a configurable number of calls within a transaction and logging a warning so that’s clear.

- Reducing memory usage by deduplicating identical queries.

**Comment by binaryseed** [comment]
https://hexdocs.pm/new_relic_agent/NewRelic.html#start_transaction/2

> Do not use this for processes that live a very long time, doing so will risk a memory leak tracking attributes in the transaction!

**Comment by binaryseed** [comment]
I'll look at doing an optimization or two to improve things...

**Comment by binaryseed** [comment]
Actually, this particular issue you point out in the screenshots is already optimized in https://github.com/newrelic/elixir_agent/pull/284

**Comment by binaryseed** [comment]
(And doing per-transaction limits wasn't possible in an efficient way before that same PR)

**Comment by tomtaylor** [comment]
> https://hexdocs.pm/new_relic_agent/NewRelic.html#start_transaction/2
> 
> > Do not use this for processes that live a very long time, doing so will risk a memory leak tracking attributes in the transaction!

Thanks - I hadn’t spotted that. It’s not immediately clear to me whether 15 mins is ‘very long’. An example might help here?

> (And doing per-transaction limits wasn't possible in an efficient way before that same PR)

Great!
