### ISSUE TITLE
External Services are not listed

### ISSUE THREAD

**Issue by Aduril** [newrelic/elixir_agent#310]
Hey there folks,

**Describe the bug**

I encountered a strange behaviour regarding the listing of `External Service` calls within the New Relic APM Monitor. Chances are that I am holding this completly wrong, so please illuminate my shrouded mind :) :

I implemented the example from the README.md:

```
defmodule MyExternalService do
  use NewRelic.Tracer

  @trace {:request, category: :external}
  def request(method, url, headers) do
    NewRelic.set_span(:http, url: url, method: method, component: "HTTPoison")

    headers = headers ++ NewRelic.distributed_trace_headers(:http)

    HTTPoison.get(url, headers)
  end
end
```
and called it.
I saw that the request was visible in the chart on the right side of `External Services`, but there is no entry within the list on the left side.
<img width="1175" alt="Screenshot 2021-02-16 at 11 07 42" src="https://user-images.githubusercontent.com/24710449/108058769-ca634800-7054-11eb-8a0b-7ab9b7ffef2f.png">

My question is: Is that an expected behaviour? What do I need to do to have a list of called external services?

**Background**

I like to monitor the timings of external services that are used by my phoenix application and to set alerts if they start to slow down. Further advice regarding this is well received. :)

**Environment**
* Elixir & Erlang version (`elixir -v`): Erlang/OTP 23 [erts-11.1.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace] Elixir 1.11.3 (compiled with Erlang/OTP 23)
* Agent version (`mix deps | grep new_relic_agent`): new_relic_agent 1.22.2 (Hex package) (mix)

Thanks for your help 
Kind regards
Peter

**Comment by binaryseed** [comment]
Hi, can you send me an email at vince@ and I can take a closer look?

**Comment by Aduril** [comment]
I think the domain part is missing there 😬 Shall I guess or do you mind repairing it? 😄

**Comment by binaryseed** [comment]
Yeah, it's newrelic.com :)

**Comment by binaryseed** [comment]
FYI, this wasn't an issue with External Services but a "metric explosion" which led to new metrics getting blocked
