### ISSUE TITLE
Reporting transaction name clearly

### ISSUE THREAD

**Issue by sb8244** [newrelic/elixir_agent#32]
**Describe the bug**

When using `NewRelic.set_transaction_name/1`, I expect that the output transaction name is visually correct in New Relic. However, it seems to not match with the recommended way of setting a name. For example:

```
NewRelic.set_transaction_name("GET//OkrViewController/show")
```

should produce a GET transaction called `OkrViewController/show`. In practice, the leading `//` is kept, even though the GET/POST/PUT is picked up correctly:

![image](https://user-images.githubusercontent.com/1231659/46328373-e6c1cf80-c5d4-11e8-91ef-184700101c84.png)

**Environment**
* Elixir & Erlang version (`elixir -v`):
```
Erlang/OTP 20 [erts-9.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.7.3 (compiled with Erlang/OTP 20)
```
* Agent version (`mix deps | grep new_relic_agent`): `new_relic_agent 1.0.2 (Hex package) (mix)`

**Comment by binaryseed** [comment]
Ahh, this might be just a documentation fix. The first segment of the name gets chopped off and translated into a namespace..

The remaining part doesn't have to follow any other convention, it can be anything you want, so you are probably going to want something more like this:

```elixir
NewRelic.set_transaction_name("Phoenix/ActiveUserController/show")
```

**Comment by sb8244** [comment]
Perfect, will try this out!
