### ISSUE TITLE
Error Reporter Optional

### ISSUE THREAD

**Issue by sb8244** [newrelic/elixir_agent#33]
**Is your feature request related to a problem? Please describe.**
Error reports that contain session information can be considered sensitive and often not desired to be stored in any third party.

**Describe the solution you'd like**
Either: disable the error reporter from starting **or** be able to filter out certain error types from the error.

2 This could potentially be difficult depending on the type of error. For instance, an unmatched clause in a phoenix controller will raise an error with the entire plug contents (including session)

**Describe alternatives you've considered**
The sasl logger could be manually removed at application boot time. This may actually be an acceptable answer, but could end up re-initializing the error handler if the new relic application crashes and restarts.

**Comment by sb8244** [comment]
I should add that I'm happy to PR this with some 👍on the idea. I've done this in the past by checking the config to dynamically build the supervised child list.

**Comment by binaryseed** [comment]
Yeah, I'd be open to a PR that made these lines conditional:

https://github.com/newrelic/elixir_agent/blob/f35f94920b08fedc4b57bc1cec7d5e179f6de359/lib/new_relic/error/supervisor.ex#L17-L18

Error Logger uses handlers so if we don't install one we won't get any error reports.

Ideally, it'd be a simple `Application.get_env(:new_relic_agent, :disable_error_reporting, false)` check

Thanks!

**Comment by binaryseed** [comment]
Hmm, right.

We have to call `Reporter.stop/1`, skipping that would mean the transaction doesn't get reported, and it'd leak memory.

You could handle this by putting the condition inside `handle_errors` https://github.com/newrelic/elixir_agent/blob/45a067c6e53c157f728fd6b06b534a02a997ef5a/lib/new_relic/transaction.ex#L44-L48

Calling `Reporter.stop(errors)` will report, but if you call `Reporter.stop(conn)` it won't report any errors

**Comment by sb8244** [comment]
Working through tests now https://github.com/newrelic/elixir_agent/compare/master...sb8244:disable-errors?expand=1

My idea is to keep the txn as `error: true` so that information is present in New Relic. However, the error information is not added to the attributes.
