### ISSUE TITLE
Table name parsing error causes Ecto telemetry handler to detach

### ISSUE THREAD

**Issue by tomtaylor** [newrelic/elixir_agent#339]
**Describe the bug**

We're seeing a handful of errors which cause the New Relic agent Ecto handler to detach:

```
Handler {:new_relic_ecto, Poplar.Repo} has failed and has been detached. Class=:error
Reason=:function_clause
Stacktrace=[
  {String, :replace, [nil, ["\"", "`", "[", "]"], "", []],
   [file: 'lib/string.ex', line: 1447]},
  {NewRelic.Telemetry.Ecto.Metadata, :parse_query, 1,
   [file: 'lib/new_relic/telemetry/ecto/metadata.ex', line: 39]},
  {NewRelic.Telemetry.Ecto.Metadata, :parse, 1,
   [file: 'lib/new_relic/telemetry/ecto/metadata.ex', line: 11]},
  {NewRelic.Telemetry.Ecto.Handler, :handle_event, 4,
   [file: 'lib/new_relic/telemetry/ecto/handler.ex', line: 32]},
  {:telemetry, :"-execute/3-fun-0-", 4,
   [file: '/tmp/build_abc31da8/deps/telemetry/src/telemetry.erl', line: 135]},
  {:lists, :foreach, 2, [file: 'lists.erl', line: 1342]},
  {Ecto.Adapters.SQL, :log, 4, [file: 'lib/ecto/adapters/sql.ex', line: 911]},
  {DBConnection, :log, 5, [file: 'lib/db_connection.ex', line: 1460]}
]
```

It looks like this might have been introduced in `1.25.1` with the [table name parsing fix](https://github.com/newrelic/elixir_agent/commit/c64328aff6c57276eeed31459f75578ef201ebe8#diff-4da89e94e5b7e683ca4c3d89946a717b52ebe0c0aa50b80eda26b3339382b589R67).

**Environment**

* Elixir & Erlang version (`elixir -v`): 1.11.4, OTP 23.1
* Agent version (`mix deps | grep new_relic_agent`): 1.25.1

**Comment by binaryseed** [comment]
Hi, sorry about that, any chance you have the SQL of the query in a log line above? the regex must not be matching..

**Comment by tomtaylor** [comment]
I think it might be `SELECT pg_try_advisory_xact_lock($1)` that Oban fires when the application boots.

**Comment by binaryseed** [comment]
Great, I can fix this

**Comment by binaryseed** [comment]
https://github.com/newrelic/elixir_agent/pull/340
