### ISSUE TITLE
cannot start my app due to new_relic_agent crashing

### ISSUE THREAD

**Issue by epinault** [newrelic/elixir_agent#341]
**Describe the bug**
I have upgraded to the latest version . Just trying to start my app with mix phx.server and it crashes with the following 

```
** (Mix) Could not start application new_relic_agent: exited in: NewRelic.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function NewRelic.Harvest.Collector.Protocol.determine_host/2 is undefined (module NewRelic.Harvest.Collector.Protocol is not available)
            NewRelic.Harvest.Collector.Protocol.determine_host(nil, nil)
            (new_relic_agent 1.25.2) lib/new_relic/init.ex:27: NewRelic.Init.init_config/0
            (new_relic_agent 1.25.2) lib/new_relic/init.ex:9: NewRelic.Init.run/0
            (new_relic_agent 1.25.2) lib/new_relic/application.ex:7: NewRelic.Application.start/2
            (kernel 7.2) application_master.erl:277: :application_master.start_it_old/4
 ```

**Environment**
* Elixir & Erlang version (`elixir -v`):
   erErlang/OTP 23 [erts-11.1.8] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
   Elixir 1.11.3 (compiled with Erlang/OTP 23)
* Agent version (`mix deps | grep new_relic_agent`):  1.25.2

**Comment by epinault** [comment]
FYI, I had to clean the 1.24 and reinstally 1.25 and seems to compile and run now. So something bizzarre in that upgrade

**Comment by binaryseed** [comment]
What was the old version you were running?

I don't see anything that's changed that could have triggered this, that function was added in `1.23.0`

**Comment by epinault** [comment]
It was 1.23.6 . I have not idea why it fails either. but a clean recompilation fixed so I am also curious why
