### ISSUE TITLE
Number of Processes explodes.

### ISSUE THREAD

**Issue by Aduril** [newrelic/elixir_agent#349]
Hello @binaryseed ,
**Describe the bug**

My team and I recently upgraded our newrelic agent from 1.23.6 to 1.27.0 and removed new_relic_phoenix (0.3.0) as suggested within the package.

Unfortunatly this resultet in an steady increase of beam processes within our live environment, as can be seen here:
<img width="753" alt="Screenshot 2021-05-22 at 17 07 28" src="https://user-images.githubusercontent.com/24710449/119231355-c8f85e80-bb20-11eb-885d-2fe3a1216d3d.png">

Are there some steps to consider when upgrading or is this a bug?

Kind regards,
Peter

**Environment**
* Elixir & Erlang version (`elixir -v`): Erlang/OTP 23 [erts-11.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace] Elixir 1.11.4 (compiled with Erlang/OTP 23)
* Agent version (`mix deps | grep new_relic_agent`): new_relic_agent 1.23.6 -> 1.27.0

**Comment by binaryseed** [comment]
A recent change means that there will be 1 agent "sidecar" process per Transaction in your app, and it will live while the Transaction process lives. 

The number of processes that the BEAM can handle is quite large - so alone this isn't necessarily a problem, did you see any adverse effects during this time like memory usage or CPU?
