### ISSUE TITLE
Transaction summary PID not clear

### ISSUE THREAD

**Issue by sahilpaudel-pe** [newrelic/elixir_agent#356]
Hi,

When I go to a particular transaction summary I can see that what are components and how much time it took to complete
I can see queries and all which is fine but recently I have seeing PID in that summary table and it is taking a huge chunk of time as mentioned by it, and I am unable to understand what is that.

Please see the attached screenshot for detail

<img width="1067" alt="Screenshot 2021-07-13 at 8 53 37 AM" src="https://user-images.githubusercontent.com/59870822/125385363-f7bfe200-e3b7-11eb-9a46-2466d8d0b5f5.png">

Please let me know if more details are required to understand this.

Thanks.

**Environment**
* Elixir & Erlang version (`elixir -v`): "1.8",
* Agent version (`mix deps | grep new_relic_agent`):  {:new_relic_agent, "~> 1.17.1"},

**Comment by binaryseed** [comment]
This means that a linked process was spawned during the transaction, does that ring any bells?
