### ISSUE TITLE
Reporting dimensional metrics using report_metric

### ISSUE THREAD

**Issue by tpitale** [newrelic/elixir_agent#368]
I'm not sure if the current implementation only supports metrics of the `Custom/<category>/<name>` format, or if `NewRelic.report_metric` could be used to report metrics with attributes.

Docs for the metric API: https://docs.newrelic.com/docs/data-apis/ingest-apis/metric-api/report-metrics-metric-api/

**Comment by tpitale** [comment]
Looks like this might best fit in with other `TelemetrySdk` features.

I think my only question is what should the interface look like since we already have `NewRelic.report_custom_metric`. Thinking maybe something like `NewRelic.increment_counter_metric` or `NewRelic.report_gauge` or something? Looks like types are `count`, `gauge` and `summary`.

**Comment by binaryseed** [comment]
Yep, using `TelemetrySdk` is the right path.. there's a good pattern going with Logs & Traces already. You'll also have to create a Harvester that collects & aggregates the metrics.. For Timeslice metrics, `NewRelic.Harvest.Collector.Metric.Harvester` has a very optimized implementation using `:counters` that could be copied

I'd create new `NewRelic` functions for this so the two metric types aren't confused, maybe something like `report_dimensional_metric(:count, name, value, attributes)`?

**Comment by tpitale** [comment]
Within a single harvest cycle, when we merge metrics with the same type + name … should we merge the attributes? That doesn't seem right. I guess only if type + name + attributes match, would we then combine for a single harvest?

**Comment by tpitale** [comment]
Maybe some value in finding the common attributes and moving them into the `common` block to save on transmission size?

**Comment by binaryseed** [comment]
This was added to the agent a while back
