### ISSUE TITLE
Support Phoenix 1.6

### ISSUE THREAD

**Issue by lukashambsch** [newrelic/elixir_agent#372]
**Is your feature request related to a problem? Please describe.**
I'm upgrading a project to Phoenix 1.6 and it looks like this package is not compatible.

**Describe the solution you'd like**
If the current codebase is compatible, it might be as simple as updating the dependency.

**Comment by binaryseed** [comment]
What are you observing? I don't know of any incompatibility issues with 1.6

**Comment by anthonator** [comment]
@lukashambsch are you specifying a version of `:telemetry` older than `1.0` in `mix.exs`? This caused some issues for us.

**Comment by lukashambsch** [comment]
I missed these responses, sorry for the slow reply. After upgrading everything else I added `new_relic_agent` back in and it's working now. It must have been something I was doing wrong. To the question about `telemetry`, I don't actually have that specified in my `mix.exs` at all, just `telemetry_metrics` and `telemetry_polling`. But it looks like it's installing `0.4.3`. When I try to upgrade to `1.0` I get an incompatibility error with `ecto_sql`.

Anyways, I'm going to go ahead and close this as user error. Thanks for the quick responses!
