### ISSUE TITLE
Incompatible with Elixir 1.8.x

### ISSUE THREAD

**Issue by akagr** [newrelic/elixir_agent#382]
**Describe the bug**
The readme and mix file mention a minimum requirement of Elixir 1.8. However the code uses `System.pid/0`, which was [introduced in Elixir 1.9.0](https://hexdocs.pm/elixir/main/System.html#pid/0).

This was introduced since https://github.com/newrelic/elixir_agent/pull/373

**Environment**
* Elixir & Erlang version: v1.8
* Agent version: v1.27.7

**Comment by binaryseed** [comment]
Updating compatible elixir versions here: https://github.com/newrelic/elixir_agent/pull/383
