### ISSUE TITLE
Allow Configuration of CA Certificates

### ISSUE THREAD

**Issue by JamieMaclean** [newrelic/elixir_agent#387]
**Is your feature request related to a problem? Please describe.**
We have a use case for needing to configure the `cacertfile` being used to connect to New Relic. Currently inside the module`NewRelic.Util.HTTP` this cannot be configured. As a result we are getting the following error on start up: 

```
[ERROR] - preconnect: (failed_request) {:failed_connect, [{:to_address, {'collector.eu01.nr-data.net', 443}}, {:inet, [:inet], {:tls_alert, {:unknown_ca, 'TLS client: In state wait_cert_cr at ssl_handshake.erl:2098 generated CLIENT ALERT: Fatal - Unknown CA\n'}}}]}
```

**Describe the solution you'd like**
Allow the `cacertfile` to be configured via the project config and use `CAStore.file_path()` as the fallback. I see that a similar configuration is possible for some of the other agents e.g. the Java agent (https://docs.newrelic.com/docs/apm/agents/java-agent/configuration/configuring-your-ssl-certificates/).

**Describe alternatives you've considered**
Currently we don't really have an alternative other than to fork the repo and change that line.

I'm more than happy to open a PR on this issue. Let me know.

**Comment by mattbaker** [comment]
@JamieMaclean would @edds work in #391 solve this for you? I saw it mentioned in the PR

**Comment by JamieMaclean** [comment]
> @JamieMaclean would @edds work in #391 solve this for you? I saw it mentioned in the PR

It certainly does. Thank you! I'll close this issue.

**Comment by mattbaker** [comment]
just published https://hex.pm/packages/new_relic_agent/1.27.8
