### ISSUE TITLE
Dumb question about crashes

### ISSUE THREAD

**Issue by ferigis** [newrelic/elixir_agent#399]
**Describe the bug**
We have a cron job running every night. This process crashes sometimes and we would like to monitor the crashes on new relic.

As this is not a web/ecto... process we have to deal with it in a different way. I tried something like this:

```elixir
...
:ok = NewRelic.start_transaction("MyCategory", "MyName")
... Code which may crash here...
NewRelic.stop_transaction()
```

but the errors are not displayed on New Relic dashboard.

How can we "monitor" this process to publish data to NR?

Thanks!

**Environment**
* Elixir & Erlang version (`elixir -v`): 1.14.3
* Agent version (`mix deps | grep new_relic_agent`): 1.27.8

**Comment by tpitale** [comment]
You might be able to try some of the stuff I suggest here to enable debug logging: https://github.com/newrelic/elixir_agent/issues/364#issuecomment-983953260

Look for log lines about events harvested.

**Comment by binaryseed** [comment]
You also need to make sure the agent is started. 

If you use a mix task, you can `use NewRelic.Instrumented.Mix.Task `... see https://github.com/newrelic/elixir_agent?tab=readme-ov-file#pre-instrumented-modules It ensures the agent is started and stopped.

If not you can do something similar...
```elixir
Application.ensure_all_started(:new_relic_agent)
NewRelic.Harvest.Collector.AgentRun.ensure_initialized()
NewRelic.start_transaction("Category", "Name")

# ...

NewRelic.stop_transaction()
Application.stop(:new_relic_agent)
```
