### ISSUE TITLE
Proxy configuration

### ISSUE THREAD

**Issue by keshav-c** [newrelic/elixir_agent#403]
**Is your feature request related to a problem? Please describe.**
How can I configure this agent to use a proxy when connecting to the internet. 

I tried to configure `:httpc` with proxy settings in my app like so:

_config/releases.exs_
```
:httpc.set_options(proxy: {{'http://www.myproxy.com`, 3138}, []})
```
But I get the error in my logs
```
{
	"application":"my-app","env":"prod","level":"ERROR",
	"message":"new_relic_agent - preconnect: (failed_request) {:failed_connect, [{:to_address, {'collector.newrelic.com', 443}}, {:inet, [:inet], :timeout}]}",
	"mfa":"{NewRelic.Logger, :handle_cast, 2}",
	"service":"pixel","timestamp":"2023-08-11T07:53:55.013Z"
}
```

**Describe the solution you'd like**
The node.js agent has an environment variable that can be configured for this purpose. `NEW_RELIC_PROXY_URL`

**Describe alternatives you've considered**
Should this agent be patched so the proxy settings are read in the _lib/new_relic/init.ex_ file ?

**Comment by binaryseed** [comment]
The supports passing in `httpc` options that will be used:
- https://github.com/newrelic/elixir_agent/tree/master?tab=readme-ov-file#http-client-settings
