### ISSUE TITLE
Is Bandit HTTP server supported?

### ISSUE THREAD

**Issue by sgessa** [newrelic/elixir_agent#415]
I have a phoenix application using `bandit` as HTTP server instead of the default `cowboy`.
When using `bandit` the transactions are not showing in the NewRelic APM dashboard.
Is this not supported or there are extra configuration needed to make the agent work with `bandit` ?

Thanks!

**Comment by rodrigocaldeira** [comment]
Hey.

I've made some changes in this [branch](https://github.com/newrelic/elixir_agent/compare/master...rodrigocaldeira:elixir_agent:master) and it sent data to NewRelic from my application normally.

It is an experimental change for now and I don't have deep knowledge about NewRelic integration, so I can't ensure it is working properly. Please, feel free to comment about it.

**Comment by sgessa** [comment]
@rodrigocaldeira thanks for taking the time to look into this. Have you tested it yet?
I am no export also but the code looks good to me. If it works, I would only try to dry it up a bit.

For example instead of duplicating methods like this, we could do:

```elixir
  defp maybe_report_queueing(meta, server) do
    headers = get_headers(meta, server)

    with true <- NewRelic.Config.feature?(:request_queuing_metrics),
         request_start when is_binary(request_start) <- headers[@request_start_header],
         {:ok, request_start_s} <- Util.RequestStart.parse(request_start) do
      NewRelic.add_attributes(request_start_s: request_start_s)
    end
  end

  defp get_headers(meta, :bandit) do
    Map.new(meta.conn.req_headers)
  end

  defp get_headers(meta, :cowboy) do
    meta.req.headers
  end
```

To avoid duplicating `handle_event` functions maybe we could group the events, e.g.:

```elixir
  def handle_event(
        [server, :request, :start],
        %{monotonic_time: monotonic_time},
        meta,
        _config
      ) do

    Transaction.Reporter.start_transaction(:web)

    if NewRelic.Config.enabled?(),
      do: DistributedTrace.start(:http, get_headers(meta, server))

    add_start_attrs(meta, monotonic_time, server)
    maybe_report_queueing(meta, server)
  end

  def handle_event(
        [server, :request, :stop],
        %{duration: duration} = meas,
        meta,
        _config
      ) do
    add_stop_attrs(meas, meta, duration, server)
    add_stop_error_attrs(meta)

    Transaction.Reporter.stop_transaction(:web)
  end
```

Just an idea, let me know what you think :smile:

**Comment by rodrigocaldeira** [comment]
@sgessa Yeah! You are absolutely right.

Yes, I've tested it and it sent web transactions' data to NewRelic.

I'm going to apply your changes, test it again, and post the results here ASAP.

Thanks for your time to answer this!

**Comment by rodrigocaldeira** [comment]
@sgessa I applied the suggested changes and it seems to be working properly.

The tests were done using cowboy and Bandit as well.

![image](https://github.com/user-attachments/assets/da55e3c3-c19f-4c30-b5dc-510260844a5f)

**Comment by sgessa** [comment]
Awesome! Perhaps it's time to open a PR :rocket:

**Comment by rodrigocaldeira** [comment]
Done!
Thanks a lot @sgessa !
