### ISSUE TITLE
Errors not recorded since upgrading to Elixir 1.15

### ISSUE THREAD

**Issue by tmaszk** [newrelic/elixir_agent#419]
**Describe the bug**
Elixir errors are not sent to New Relic since upgrading to Elixir 1.15

**Environment**
* Elixir 1.15.7  Erlang OTP 26
* Agent version 1.28.0

**Comment by tpitale** [comment]
@tmaszk I'm going to try to start looking at this. Any other details you might have would be much appreciated!

**Comment by tpitale** [comment]
I think you already fixed this change in work you did for #421 https://hexdocs.pm/elixir/1.15/changelog.html#integration-with-erlang-otp-logger

**Comment by tmaszk** [comment]
I think you are correct.  I added a comment to https://github.com/newrelic/elixir_agent/pull/421 https://hexdocs.pm/elixir/1.15/changelog.html#integration-with-erlang-otp-logger about how a configuration change the user would need to make.

**Comment by tpitale** [comment]
Merged #426 and #427
