### ISSUE TITLE
Failed to send harvest

### ISSUE THREAD

**Issue by sgessa** [newrelic/elixir_agent#431]
**Describe the bug**
The agent seems to be working because data is showing in NewRelic but we are getting a lot of errors:

```
08:25:41.483 [error] new_relic_agent - Failed to send harvest from NewRelic.Harvest.Collector.TransactionEvent.HarvesterSupervisor
08:25:41.489 [error] new_relic_agent - Failed to send harvest from NewRelic.Harvest.Collector.TransactionErrorEvent.HarvesterSupervisor
09:07:44.842 [error] new_relic_agent - Failed to send harvest from NewRelic.Harvest.Collector.CustomEvent.HarvesterSupervisor
```

Occasionally we also get some of these:

```
20:42:56.535 [error] new_relic_agent - error_event_data: (failed_request) {:failed_connect, [{:to_address, {~c"collector.newrelic.com", 443}}, {:inet, [:inet], :timeout}]}
03:47:10.771 [error] new_relic_agent - analytic_event_data: (503) unexpected_response - {}
```

What the reason could be? Is there a way to temporarily silence these errors?

**Environment**
* Elixir 1.15.7 (compiled with Erlang/OTP 26)
* new_relic_agent 1.29.0

**Comment by binaryseed** [comment]
I'm guessing these were transient errors because the NewRelic backend was experiencing issues. Feel free to chime in again if it looks like something in the agent is going wrong
