### ISSUE TITLE
Git tag v1.29.0 is missing from the repository

### ISSUE THREAD

**Issue by axelson** [newrelic/elixir_agent#452]
**Describe the bug**
Currently visiting: https://hexdocs.pm/new_relic_agent/NewRelic.Instrumented.Task.html
- And then clicking on the "view code" icon brings you to
- https://github.com/newrelic/elixir_agent/blob/v1.29.0/lib/new_relic/instrumented/task.ex#L1
- Which is a 404 because `v1.29.0` is not pushed as a git tag

Also the docs for 1.30.0 don't appear to have been pushed to hexdocs.

**Environment**
N/A

**Comment by binaryseed** [comment]
Fixed tag https://github.com/newrelic/elixir_agent/tree/v1.29.0

**Comment by binaryseed** [comment]
Fixed docs https://hexdocs.pm/new_relic_agent/1.30.0/readme.html

**Comment by axelson** [comment]
Great, thank you!
