### ISSUE TITLE
database transaction

### ISSUE THREAD

**Issue by MeterSoft** [newrelic/elixir_agent#53]
i added include plug `use NewRelic.Transaction` to my project but i did not see database details. Should i config something else?

**Comment by binaryseed** [comment]
We don't auto-instrument any database calls. There's a `new_relic_ecto` instrumentation library in the works but it's still early stages

You can always add function tracers to any function call you want and it'll show up:
https://hexdocs.pm/new_relic_agent/NewRelic.Tracer.html

**Comment by MeterSoft** [comment]
i added function trace to function with database call but it not visible database detail on ui.

**Comment by relistan** [comment]
@MeterSoft they won't show up as database calls if you're instrumenting them with the function tracer. You'll have to look at them as normal function calls. Sounds like @binaryseed is saying they are working on Ecto instrumentation, and that would then most likely show up in the DB detail.
