### ISSUE TITLE
It is possible to track background functions in workers?

### ISSUE THREAD

**Issue by MeterSoft** [newrelic/elixir_agent#54]

**Comment by binaryseed** [comment]
What do you mean by background functions / workers? Everything in Elixir is concurrent so i'm not sure what would be background...

The agent has function tracers and the ability to generate custom events already.. so you can instrument things at will.

Check out: 
https://hexdocs.pm/new_relic_agent/NewRelic.Tracer.html
https://hexdocs.pm/new_relic_agent/NewRelic.html#report_custom_event/2

**Comment by MeterSoft** [comment]
i have in main supervisor `supervisor(Scraper.Task, [50])`. it is Genstage
in task i added `use NewRelic.Tracer` and `@trace :fetch_from`. This function is loop. But it is not visible in newrelic ui.

**Comment by binaryseed** [comment]
Traces categorized as `:external` will show up in the Externals page of the UI

```elixir
@trace {:query, category: :external}
```

Tracers without a category show up in Transaction Traces and as Insights events
