### ISSUE TITLE
CompileError in Module App

### ISSUE THREAD

**Issue by vanegomez** [newrelic/elixir_agent#57]
**Describe the bug**
I was wondering if the error I'm getting is due to old deps. Upgraded Elixir from 1.3.4 to 1.7.3 to be able to use new relic's agent 

```
== Compilation error in file lib/employer_gateway.ex ==
** (RuntimeError) no routes defined in module MyApp using Plug.Router
    (plug) expanding macro: Plug.Router.__before_compile__/1
    lib/my_app.ex:1: MyApp (module)
    (elixir) lib/kernel/parallel_compiler.ex:206: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```
Deps

```
defp deps do
    [
      {:cors_plug, "~> 1.2"},
      {:cowboy, "~> 2.0"},
      {:credo, "~> 0.3", only: [:dev, :test]},
      {:excoveralls, "~> 0.5", only: :test},
      {:gettext, "~> 0.9"},
      {:httpoison, "~> 1.0"},
      {:jiffy, "~> 0.14.7", override: true},
      {:joken, "~> 1.5.0"},
      {:jose, "~> 1.3"},
      {:maru, "~> 0.13"},
      {:new_relic_agent, "~> 1.2.0"},
      {:phoenix, "~> 1.4"},
      {:poison, "~> 2.2.0"}, # here be dragons
      {:plug, "~> 1.6"},
      {:pubsub_client, "~> 0.3.1", git: "git@github.com:itriage/pubsub_elixir_client.git", tag: "test-elixir-1.7-rc.0" },
      {:uuid, "~> 1.1"}
   ]
  end
```

**Environment**
Development

* Elixir & Erlang version (`elixir -v`): Elixir 1.7.3
* Agent version (`mix deps | grep new_relic_agent`):

**Comment by vanegomez** [comment]
Hi, I'm super new with Elixir. I think it's a Phoenix app and MyApp module does not define any routes. It follows this pattern. Thank you =) 

```
defmodule MyApp do
  use Application
  use Plug.Router
  use NewRelic.Transaction

  def start(_type, _args) do
    children = []
    Supervisor.start_link(children, strategy: :one_for_one)
  end
end
```

**Comment by binaryseed** [comment]
If it's a phoenix app, check out this adapter for the agent & Phoenix:

https://github.com/binaryseed/new_relic_phoenix

**Comment by vanegomez** [comment]
I think the adapter works. Is there a way to disable it on local dev? 

Thank you =D

**Comment by binaryseed** [comment]
`Mix` can let you do that, look at the `:only` option...

https://hexdocs.pm/mix/Mix.Tasks.Deps.html#module-dependency-definition-options

**Comment by vanegomez** [comment]
You are the best. Thank you for helping this newbie out :)
