### ISSUE TITLE
Payload too large

### ISSUE THREAD

**Issue by Catharz** [newrelic/elixir_agent#61]
**Describe the bug**
We seem to be getting 413 status with an empty body from New Relic.

**Environment**
* Elixir & Erlang version (`elixir -v`):
Erlang/OTP 21 [erts-10.0.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.7.3 (compiled with Erlang/OTP 21)

* Agent version (`mix deps | grep new_relic_agent`):
new_relic_agent 1.2.0 (Hex package) (mix)
locked at 1.2.0 (new_relic_agent) ce96cb01

* Relevant log messages

```
[mana-production-5dcb56c996-k6x4l] [INFO] - 2018-11-16 07:08:36 - Completed Error Event harvest - size: 0
[mana-production-5dcb56c996-k6x4l] [INFO] - 2018-11-16 07:08:36 - Completed Error Trace harvest - size: 0
[mana-production-5dcb56c996-k6x4l] [INFO] - 2018-11-16 07:08:36 - Completed Transaction Trace harvest - size: 7
[mana-production-5dcb56c996-k6x4l] [INFO] - 2018-11-16 07:08:36 - Completed Metric harvest - size: 24
[mana-production-5dcb56c996-k6x4l] [INFO] - 2018-11-16 07:08:36 - Completed Custom Event harvest - size: 75
[mana-production-5dcb56c996-k6x4l] [INFO] - 2018-11-16 07:08:37 - Completed Transaction Event harvest - size: 58
[mana-production-5dcb56c996-k6x4l] [ERROR] - 2018-11-16 07:08:37 - (413) {}
[mana-production-5dcb56c996-k6x4l] [ERROR] - 2018-11-16 07:08:38 - (413) {}
[mana-production-5dcb56c996-k6x4l] [INFO] - 2018-11-16 07:08:38 - Completed Span Event harvest - size: 6168
```

**Comment by binaryseed** [comment]
Hi there, the 413 means Payload to Large - it's expected behavior. 

Looks like the Span Events might be the reason, you could try lowering this setting:

```elixir
config :new_relic_agent, span_event_reservoir_size: 2000
```

I'll improve that logging so we can tell which payload is being rejected

**Comment by binaryseed** [comment]
If you bump to `1.3.0`, we'll get more info about which type of data is causing payload to large
