### ISSUE TITLE
Logger formatting

### ISSUE THREAD

**Issue by ananthakumaran** [newrelic/elixir_agent#64]
**Describe the bug**
Not able to customize NewRelic.Logger formatting

Currently we have unified custom log format(json) across the org. We use [custom formatting](https://hexdocs.pm/logger/Logger.html#module-custom-formatting) and as nearly all the libraries use the standard Logger, this works without any issue.

Any specific reason for rolling custom logger instead of the standard Logger. It would be great if the library can use the standard Logger

**Environment**
* Elixir & Erlang version (`elixir -v`):

Erlang/OTP 21 [erts-10.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.7.3 (compiled with Erlang/OTP 21)
* Agent version (`mix deps | grep new_relic_agent`): 

new_relic_agent 1.2.0

**Comment by binaryseed** [comment]
We are just following standard new relic agent behavior here.

Is your request that log messages from the agent itself go through the elixir logger?

**Comment by ananthakumaran** [comment]
Yes, so we could better control how it's formatted.
