### ISSUE TITLE
Wrapping HTTPoison.Base

### ISSUE THREAD

**Issue by fbjork** [newrelic/elixir_agent#71]
Is it possible to wrap HTTPoison with New Relic instrumentation in modules where HTTPoison is wrapped with a macro already?

```elixir

defmodule Foo do
  use HTTPoison.Base
end
```

**Comment by fbjork** [comment]
@binaryseed Thoughts on adding support for macros? That way I can do `use NewRelic.Instrumented.HTTPoison` in modules without having to change the rest of my code.

**Comment by binaryseed** [comment]
The spirit of this project is to provide a foundation to build on. At this point, I don't have the bandwidth to make any further library specific instrumentation, but this is something that could be built using the capabilities the agent does provide..
