### ISSUE TITLE
Not seeing URL of external services

### ISSUE THREAD

**Issue by fbjork** [newrelic/elixir_agent#72]
Instead of seeing the URL of external services I'm tracing with the New Relic instrumentation, I'm seeing the function name, e.g `NewRelic.Instrumented.HTTPoison.get`

Am I doing something wrong or is it a bug?

<img width="1224" alt="screen shot 2018-12-05 at 10 42 41 am" src="https://user-images.githubusercontent.com/4585/49536147-b28bb900-f87a-11e8-9ceb-0f0131fe1df0.png">

**Comment by binaryseed** [comment]
That is expected, we don't support URL based stuff yet, the name comes from the `@trace` annotation, so if you put it manually on your module / function you'll get more detailed info

**Comment by fbjork** [comment]
@binaryseed Got it, would be a great addition to support out of the box:)

**Comment by fbjork** [comment]
Meanwhile, if you have an example of how to do it manually it would be very helpful for us.

**Comment by binaryseed** [comment]
All you do is add the `@trace` annotations, as shown in the docs

https://hexdocs.pm/new_relic_agent/NewRelic.Tracer.html

**Comment by fbjork** [comment]
I added `@trace {:request, category: :external}` above the `def request(method, url, body \\ "", headers \\ [], options \\ []) do` function in my HTTP client module, but it's still not showing the URL in New Relic external services.

**Comment by binaryseed** [comment]
it wont' show the URL, it will show the name of the module / function

**Comment by fbjork** [comment]
How do I get the URL to show?

**Comment by binaryseed** [comment]
that isn't supported at the moment
