### ISSUE TITLE
New Relic agent supported for services running within AWS Fargate?

### ISSUE THREAD

**Issue by hebbo** [newrelic/elixir_agent#74]
Hi there,

we don't seem to be able to run the agent from our Elixir service running from AWS Fargate.

The AWS metadata endpoint:
https://github.com/newrelic/elixir_agent/blob/master/lib/new_relic/util.ex#L68

is not available from an Fargate/ECS task as per this forum post:
https://forums.aws.amazon.com/thread.jspa?messageID=830807&tstart=0

and we are getting this error upon start of the Elixir service:

```
Elixir.ArgumentError argument error 
    gen_tcp.erl:153 :gen_tcp.connect/4
    APP_PATH/deps/hackney/src/hackney_connect.erl:247 :hackney_connect.do_connect/5
    APP_PATH/deps/hackney/src/hackney_connect.erl:37 :hackney_connect.connect/5
    APP_PATH/deps/hackney/src/hackney.erl:316 :hackney.request/5
    lib/httpoison/base.ex:630 HTTPoison.Base.request/9
    lib/new_relic/util.ex:80 NewRelic.Util.aws_vendor_hash/1
    lib/new_relic/util.ex:71 NewRelic.Util.maybe_add_vendors/2
    lib/new_relic/harvest/collector/agent_run.ex:62 NewRelic.Harvest.Collector.AgentRun.connect_payload/0
```

Is Fargate not supported yet or are we missing anything?

Thanks!
Angel

**Environment**
```
Erlang/OTP 21 [erts-10.0.5] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]

Elixir 1.7.2 (compiled with Erlang/OTP 21)
```
* Agent version 1.3.1

**Comment by hebbo** [comment]
For context, seems like indeed the metadata endpoints in Fargate sit at a different location:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v2.html

**Comment by binaryseed** [comment]
What version of `hackney` is installed?

**Comment by hebbo** [comment]
Yeah. Seems like there is something else going on here.

The Hackney version in use is 1.14.3.
The Httpoison version is 1.4.0.

Cheers

**Comment by hebbo** [comment]
Hi @binaryseed 
Is it safe to assume that the elixir agent for New Relic is not compatible with services running in ECS Fargate? (which seem to have a different API available to retrieve metadata).

Thanks!

**Comment by binaryseed** [comment]
The agent should run anywhere safely, but that PR doesn't fetch the metadata from the newer API, so there might be implications there regarding host detection. We're still looking into that, I don't think an NR agents hit that newer API yet
