### ISSUE TITLE
Report Heroku Dyno name

### ISSUE THREAD

**Issue by fbjork** [newrelic/elixir_agent#77]
It would be nice to get Heroku Dyno names reported to New Relic (web.1, web.2 etc).

Here's how we solved it in New Relixir:
https://github.com/TheRealReal/new-relixir/commit/445272877bb5d61d3573920af74e40d3d417f0f3

**Comment by binaryseed** [comment]
There is a specific way NR handles heroku dyno names in other agents (ex: https://docs.newrelic.com/docs/agents/ruby-agent/installation/ruby-agent-heroku)

There are 2 config properties we'd have to support:

`use_dyno_names` and `dyno_name_prefixes_to_shorten`
