### ISSUE TITLE
Non-web transactions tracing

### ISSUE THREAD

**Issue by barthez** [newrelic/elixir_agent#83]
**Is your feature request related to a problem? Please describe.**
I would like to have Non-web transactions represented in NewRelic transactions list. As an example, I would like to see [ConsumerSupervisor](https://hexdocs.pm/gen_stage/ConsumerSupervisor.html) children processes as transactions.

**Describe the solution you'd like**
It would be great to have module `NewRelic.NonWebTransaction` which I could use in my module and then annotate function, which I would like to create transaction for (similar to NewRelic.Trace, but created transaction instead of trace span).

I would be eager to help implementing it.

**Describe alternatives you've considered**
I'm wrapping my functions with something like:
```elixir
def new_relic_transaction(name, fun) do
  NewRelic.Transaction.Reporter.start()
  NewRelic.set_transaction_name(name)
  fun.()
after
  conn = %Plug.Conn{method: "NONWEB"} # Fake connection
  NewRelic..Transaction.Reporter.stop(conn)
end
```

But it does report transactions as `Web`.

**Comment by binaryseed** [comment]
When tracking a transaction, it's critical that we know when it stops, if we miss a `stop` that means we have a memory leak.. Also if your process is long-lived, we have a memory leak.

Are you trying to track the work that an individual process does, or are you trying to track a subset of work that happens in a process which stays alive and goes on to do more work?

**Comment by binaryseed** [comment]
We can track the work of an entire process, but given that some of the reporting mechanisms are async (errors, connecting spawned processes), we can't reliably split up multiple transactions in a single process (which is why we can't support cowboy 1 see #10 )

For the logic of a single function, I recommend using a Function Tracer which will show up as segments in a Transaction or as call stats if it's not in a Transaction

**Comment by barthez** [comment]
Thanks, understood. I even noticed messed up transactions I created for `handle_call`. 

Can't wait for #84 to be merged and released.
