### ISSUE TITLE
Apdex reporting

### ISSUE THREAD

**Issue by emerleite** [newrelic/elixir_agent#86]
**Describe the bug**
No Apdex sample is reported by Agent so we can't use thresholds and alert conditions based on this metric.

**Environment**
* Elixir 1.7.4 & Erlang 21
* Agent version (1.6.2)

**Comment by binaryseed** [comment]
Correct, the agent doesn't attempt to calculate an apdex score yet

**Comment by binaryseed** [comment]
Yeah, the Apdex T value is configured in the UI:

https://docs.newrelic.com/docs/apm/new-relic-apm/apdex/change-your-apdex-settings

Hope that helps

**Comment by emerleite** [comment]
I know this UI, but for Elixir Apps, there is no other option than the application name.

**Comment by binaryseed** [comment]
Oh, interesting - I'll have to look into that.

You can also configure this via `config :new_relic_agent, apdex_t: 2.5` in the meantime... The value is in seconds

**Comment by emerleite** [comment]
Thanks :)

**Comment by jozefvaclavik** [comment]
Would be cool to put this in readme.
