### ISSUE TITLE
@trace directives cause compilation warnings.

### ISSUE THREAD

**Issue by Catharz** [newrelic/elixir_agent#90]
**Describe the bug**
When I add the `@trace` directive before a function I get an unused variable warning for `args` on the following code.

```
  @trace {:get_user_details, category: :external}
  def get_user_details(args = %{open_id: _}, headers) do
    "/api/public/v2/user/details"
    |> get(add_open_id_header(headers, args))
    |> handle_response(%{"data" => %User{}})
  end
```
the full warning is:
```
warning: variable "args" is unused

Note variables defined inside case, cond, fn, if and similar do not leak. If you want to conditionally override an existing variable "args", you will have to explicitly return the variable. For example:

    if some_condition? do
      atom = :one
    else
      atom = :two
    end

should be written as

    atom =
      if some_condition? do
        :one
      else
        :two
      end

Unused variable found at:
  lib/mana_web/services/user_service.ex:9
```

**Environment**
* Elixir & Erlang version (`elixir -v`):
Erlang/OTP 21 [erts-10.0.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.7.3 (compiled with Erlang/OTP 21)
* Agent version (`mix deps | grep new_relic_agent`):
new_relic_agent 1.6.2 (Hex package) (mix)
  locked at 1.6.2 (new_relic_agent) a20b514d

**Comment by binaryseed** [comment]
Have you tried swapping the `args` to the right side of the map literal?

**Comment by binaryseed** [comment]
This ^^ PR should clear up that warning
